
Showing logs for build [32mmeta-seldonio-seldon-core-pr-24-x5qch-1[0m stage [32mmeta-pipeline[0m and container [32mstep-credential-initializer-5k7kx[0m
{"level":"info","ts":1600354387.0900774,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1600354387.090751,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mmeta-seldonio-seldon-core-pr-24-x5qch-1[0m stage [32mmeta-pipeline[0m and container [32mstep-working-dir-initializer-c79bw[0m
{"level":"info","ts":1600354388.4047177,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1600354388.5290835,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mmeta-seldonio-seldon-core-pr-24-x5qch-1[0m stage [32mmeta-pipeline[0m and container [32mstep-place-tools[0m

Showing logs for build [32mmeta-seldonio-seldon-core-pr-24-x5qch-1[0m stage [32mmeta-pipeline[0m and container [32mstep-git-source-meta-seldonio-seldon-core-pr-24-x5qch-qml27[0m
{"level":"info","ts":1600354397.0283234,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1600354403.4301462,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ 544679aaa89db2e66ab13fefd31b0baebc9d4731 in path /workspace/source"}

Showing logs for build [32mmeta-seldonio-seldon-core-pr-24-x5qch-1[0m stage [32mmeta-pipeline[0m and container [32mstep-setup-builder-home[0m

Showing logs for build [32mmeta-seldonio-seldon-core-pr-24-x5qch-1[0m stage [32mmeta-pipeline[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:544679aaa89db2e66ab13fefd31b0baebc9d4731,2450:aff0b4fc8fba8a578516cea11d026549cb2ff0f4
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git fetch origin --unshallow aff0b4fc8fba8a578516cea11d026549cb2ff0f4: 544679aaa89db2e66ab13fefd31b0baebc9d4731:
DEBUG: ran git fetch --unshallow origin aff0b4fc8fba8a578516cea11d026549cb2ff0f4: 544679aaa89db2e66ab13fefd31b0baebc9d4731: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard 544679aaa89db2e66ab13fefd31b0baebc9d4731
DEBUG: ran git reset --hard 544679aaa89db2e66ab13fefd31b0baebc9d4731 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge aff0b4fc8fba8a578516cea11d026549cb2ff0f4
error: error during merge: merging aff0b4fc8fba8a578516cea11d026549cb2ff0f4 into master: git output: Auto-merging testing/scripts/test_prepackaged_servers.py
Auto-merging operator/controllers/seldondeployment_controller.go
Auto-merging executor/cmd/executor/main.go
CONFLICT (content): Merge conflict in executor/cmd/executor/main.go
Removing examples/models/nvidia-mnist/tensorrt_mnist/mnist_labels.txt
Removing examples/models/nvidia-mnist/tensorrt_mnist/config.pbtxt
Removing examples/models/nvidia-mnist/nvidia_mnist.ipynb
Removing examples/models/nvidia-mnist/nvidia-mnist/values.yaml
Removing examples/models/nvidia-mnist/nvidia-mnist/templates/mnist_nvidia_deployment.json
Removing examples/models/nvidia-mnist/nvidia-mnist/Chart.yaml
Removing examples/models/nvidia-mnist/fetch-model.sh
Removing examples/models/nvidia-mnist/MnistTransformer.py
Removing examples/models/nvidia-mnist/Makefile
Removing examples/models/nvidia-mnist/.s2i/environment
Auto-merging doc/source/index.rst
Removing doc/source/examples/nvidia_mnist.nblink
Automatic merge failed; fix conflicts and then commit the result.: failed to run 'git merge aff0b4fc8fba8a578516cea11d026549cb2ff0f4' command in directory '', output: 'Auto-merging testing/scripts/test_prepackaged_servers.py
Auto-merging operator/controllers/seldondeployment_controller.go
Auto-merging executor/cmd/executor/main.go
CONFLICT (content): Merge conflict in executor/cmd/executor/main.go
Removing examples/models/nvidia-mnist/tensorrt_mnist/mnist_labels.txt
Removing examples/models/nvidia-mnist/tensorrt_mnist/config.pbtxt
Removing examples/models/nvidia-mnist/nvidia_mnist.ipynb
Removing examples/models/nvidia-mnist/nvidia-mnist/values.yaml
Removing examples/models/nvidia-mnist/nvidia-mnist/templates/mnist_nvidia_deployment.json
Removing examples/models/nvidia-mnist/nvidia-mnist/Chart.yaml
Removing examples/models/nvidia-mnist/fetch-model.sh
Removing examples/models/nvidia-mnist/MnistTransformer.py
Removing examples/models/nvidia-mnist/Makefile
Removing examples/models/nvidia-mnist/.s2i/environment
Auto-merging doc/source/index.rst
Removing doc/source/examples/nvidia_mnist.nblink
Automatic merge failed; fix conflicts and then commit the result.'
[31m
Pipeline failed on stage 'meta-pipeline' : container 'step-git-merge'. The execution of the pipeline has stopped.[0m
