
Showing logs for build [32mmeta-seldonio-seldon-core-pr-16-bsr2p-1[0m stage [32mmeta-pipeline[0m and container [32mstep-credential-initializer-6x5cv[0m
{"level":"warn","ts":1586203667.3618963,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1586203667.362304,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mmeta-seldonio-seldon-core-pr-16-bsr2p-1[0m stage [32mmeta-pipeline[0m and container [32mstep-working-dir-initializer-nnhx6[0m
{"level":"warn","ts":1586203668.2902143,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1586203668.2916517,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mmeta-seldonio-seldon-core-pr-16-bsr2p-1[0m stage [32mmeta-pipeline[0m and container [32mstep-place-tools[0m

Showing logs for build [32mmeta-seldonio-seldon-core-pr-16-bsr2p-1[0m stage [32mmeta-pipeline[0m and container [32mstep-git-source-meta-seldonio-seldon-core-pr-16-zx6ss[0m
{"level":"warn","ts":1586203673.41394,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1586203676.9839926,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ 3a0767c8ac5907ddb966001d7eca83cd362cffd2 in path /workspace/source"}

Showing logs for build [32mmeta-seldonio-seldon-core-pr-16-bsr2p-1[0m stage [32mmeta-pipeline[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:3a0767c8ac5907ddb966001d7eca83cd362cffd2,1670:506efe79525214522b8af8baeaaf3b33f7b2be36
DEBUG: ran git fetch --unshallow origin 506efe79525214522b8af8baeaaf3b33f7b2be36: 3a0767c8ac5907ddb966001d7eca83cd362cffd2: in 
DEBUG: ran git checkout master in 
DEBUG: ran git reset --hard 3a0767c8ac5907ddb966001d7eca83cd362cffd2 in 
DEBUG: ran clean --force -d . in 
error: error during merge: merging 506efe79525214522b8af8baeaaf3b33f7b2be36 into master: git output: Auto-merging wrappers/s2i/python/Makefile
CONFLICT (content): Merge conflict in wrappers/s2i/python/Makefile
Automatic merge failed; fix conflicts and then commit the result.: failed to run 'git merge 506efe79525214522b8af8baeaaf3b33f7b2be36' command in directory '', output: 'Auto-merging wrappers/s2i/python/Makefile
CONFLICT (content): Merge conflict in wrappers/s2i/python/Makefile
Automatic merge failed; fix conflicts and then commit the result.'
[31m
Pipeline failed on stage 'meta-pipeline' : container 'step-git-merge'. The execution of the pipeline has stopped.[0m
