
Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mpr-build-comment[0m and container [32mstep-credential-initializer-rsgm7[0m
{"level":"info","ts":1595047095.3072708,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1595047095.3081028,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mpr-build-comment[0m and container [32mstep-working-dir-initializer-22klc[0m
{"level":"info","ts":1595047095.6835594,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1595047095.6851404,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mpr-build-comment[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mpr-build-comment[0m and container [32mstep-create-dir-workspace-pwrbx[0m
{"level":"info","ts":1595047100.7166226,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1595047100.7185502,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mpr-build-comment[0m and container [32mstep-git-source-seldonio-seldon-core-pr-1921-in-m5hf6-bgpbz[0m
{"level":"info","ts":1595047101.0613139,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1595047109.0396788,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/SeldonIO/seldon-core.git @ master in path /workspace/source"}

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mpr-build-comment[0m and container [32mstep-setup-builder-home[0m

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mpr-build-comment[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:296d02420fb3010cbb7155795099d023d9c35e57,1921:774103121634cb07ccf1f7507985c12d7b548a26
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow 774103121634cb07ccf1f7507985c12d7b548a26: 296d02420fb3010cbb7155795099d023d9c35e57:
DEBUG: ran git fetch --unshallow origin 774103121634cb07ccf1f7507985c12d7b548a26: 296d02420fb3010cbb7155795099d023d9c35e57: in 
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard 296d02420fb3010cbb7155795099d023d9c35e57
DEBUG: ran git reset --hard 296d02420fb3010cbb7155795099d023d9c35e57 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 774103121634cb07ccf1f7507985c12d7b548a26
DEBUG: ran git merge 774103121634cb07ccf1f7507985c12d7b548a26 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e 296d02420fb3010cbb7155795099d023d9c35e57..HEAD
Merged SHA bc003857243581b33c754b23a9629357dc02a5a9 with commit message 'Merge commit '774103121634cb07ccf1f7507985c12d7b548a26'' into base branch master
Merged SHA 774103121634cb07ccf1f7507985c12d7b548a26 with commit message 'Helm fixups' into base branch master
Merged SHA 95cc17ebd6e5ae5feddb4067c22f4566a3176d89 with commit message 'Propagate namespace' into base branch master
Merged SHA 63e7c50c0933a834c1b9b16282c4e1f702f77d3b with commit message 'Fix ambassador test' into base branch master
Merged SHA f96a6af956d1d2615ccb5fc1e3fd1f0890fd8ef1 with commit message 'kind version and port for contour' into base branch master
Merged SHA e3ac857016ca60a4c24bfa5a954aa5560cabaeb8 with commit message 'Small ambassador fix and improve depth of testing' into base branch master
Merged SHA 9817f8bd0391901ef917d8730317dedb07918ece with commit message 'Introduce Ingress abstraction and add Contour support' into base branch master

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mpr-build-comment[0m and container [32mstep-step2[0m
+++ dirname ./add-pr-build-comment
++ cd .
++ pwd
+ STARTUP_DIR=/workspace/source/ci
+ REPO_OWNER=SeldonIO
+ REPO_NAME=seldon-core
+ PULL_NUMBER=1921
+ BUILD_NUMBER=66
+ PIPELINE_CONTEXT=integration
++ cat
+++ date
+ COMMENT_MSG='Sat Jul 18 04:38:35 UTC 2020
The logs for [integration] [66] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1921/66.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1921 --build=66'
+ ** step pr comment --owner=SeldonIO --repository=seldon-core --pull-request=1921 '--comment=Sat Jul 18 04:38:35 UTC 2020
The logs for [integration] [66] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1921/66.log

impatient try  
** get build logs SeldonIO/seldon-core/PR-1921 --build=66'

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mpr-build-comment[0m and container [32mstep-source-mkdir-seldonio-seldon-core-pr-1921-in-m5hf6-2h29x[0m
{"level":"info","ts":1595047118.9439807,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1595047118.9471576,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mpr-build-comment[0m and container [32mstep-source-copy-seldonio-seldon-core-pr-1921-in-m5hf6-xrn9v[0m
{"level":"info","ts":1595047119.191372,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1595047119.5682843,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r source/. /pvc/pr-build-comment/workspace\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mend-to-end[0m and container [32mstep-credential-initializer-jjvjr[0m
{"level":"info","ts":1595047122.4680092,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1595047122.4683928,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mend-to-end[0m and container [32mstep-working-dir-initializer-nj4wq[0m
{"level":"info","ts":1595047123.7044919,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1595047123.7058456,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mend-to-end[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mend-to-end[0m and container [32mstep-create-dir-workspace-b2b2k[0m
{"level":"info","ts":1595047129.8039227,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1595047129.8053777,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mend-to-end[0m and container [32mstep-source-copy-workspace-xhcf6[0m
{"level":"info","ts":1595047130.0410135,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1595047130.4175363,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c cp -r /pvc/pr-build-comment/workspace/. /workspace/source\"; output "}

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mend-to-end[0m and container [32mstep-setup-builder-home[0m

Showing logs for build [32mseldonio-seldon-core-pr-1921-in-m5hf6-66[0m stage [32mend-to-end[0m and container [32mstep-test-end-to-end[0m
Test run type is: [base]
Starting Docker: docker.
kind create cluster --config ../resources/kind_config.yaml
Creating cluster "kind" ...
 ‚Ä¢ Ensuring node image (kindest/node:v1.17.5) üñº  ...
 ‚úì Ensuring node image (kindest/node:v1.17.5) üñº
 ‚Ä¢ Preparing nodes üì¶  ...
 ‚úì Preparing nodes üì¶
 ‚Ä¢ Writing configuration üìú  ...
 ‚úì Writing configuration üìú
 ‚Ä¢ Starting control-plane üïπÔ∏è  ...
 ‚úì Starting control-plane üïπÔ∏è
 ‚Ä¢ Installing CNI üîå  ...
 ‚úì Installing CNI üîå
 ‚Ä¢ Installing StorageClass üíæ  ...
 ‚úì Installing StorageClass üíæ
 ‚Ä¢ Joining worker nodes üöú  ...
 ‚úì Joining worker nodes üöú
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community üôÇ
`kind get kubeconfig-path` is deprecated!

KIND will export and merge kubeconfig like kops, minikube, etc.
This command is now unnecessary and will be removed in a future release.

For more info see: https://github.com/kubernetes-sigs/kind/issues/1060
See also the output of `kind create cluster`

Files changed in python folder:
SKIPPING PYTHON IMAGE BUILD...
Files changed in operator folder:
operator/config/manager/manager.yaml
operator/config/rbac/role.yaml
operator/constants/constants.go
operator/controllers/ambassador_ingress.go
operator/controllers/ambassador_ingress_test.go
operator/controllers/cleaners.go
operator/controllers/contour_ingress.go
operator/controllers/ingress.go
operator/controllers/ingress_test.go
operator/controllers/istio.go
operator/controllers/istio_ingress.go
operator/controllers/istio_ingress_test.go
operator/controllers/seldondeployment_controller.go
operator/controllers/seldondeployment_explainers.go
operator/controllers/seldondeployment_explainers_test.go
operator/go.mod
operator/go.sum
operator/helm/split_resources.py
operator/main.go
cd ../../operator && make kind-image-install
make[1]: Entering directory '/workspace/source/operator'
go: creating new go.mod: module tmp
go: finding sigs.k8s.io v0.2.5
go: finding sigs.k8s.io/controller-tools/cmd/controller-gen v0.2.5
go: finding sigs.k8s.io/controller-tools v0.2.5
go: finding sigs.k8s.io/controller-tools/cmd v0.2.5
go: downloading sigs.k8s.io/controller-tools v0.2.5
go: extracting sigs.k8s.io/controller-tools v0.2.5
go: downloading github.com/spf13/cobra v0.0.5
go: downloading k8s.io/apimachinery v0.17.0
go: downloading k8s.io/apiextensions-apiserver v0.17.0
go: downloading github.com/gobuffalo/flect v0.2.0
go: downloading k8s.io/api v0.17.0
go: downloading sigs.k8s.io/yaml v1.1.0
go: extracting github.com/gobuffalo/flect v0.2.0
go: downloading golang.org/x/tools v0.0.0-20190920225731-5eefd052ad72
go: extracting github.com/spf13/cobra v0.0.5
go: extracting sigs.k8s.io/yaml v1.1.0
go: downloading github.com/spf13/pflag v1.0.5
go: extracting github.com/spf13/pflag v1.0.5
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: extracting k8s.io/apiextensions-apiserver v0.17.0
go: extracting k8s.io/apimachinery v0.17.0
go: extracting github.com/inconshreveable/mousetrap v1.0.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20190905181640-827449938966
go: extracting gopkg.in/yaml.v3 v3.0.0-20190905181640-827449938966
go: downloading github.com/gogo/protobuf v1.2.2-0.20190723190241-65acae22fc9d
go: downloading gopkg.in/yaml.v2 v2.2.4
go: downloading k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/google/gofuzz v1.0.0
go: extracting gopkg.in/yaml.v2 v2.2.4
go: extracting gopkg.in/inf.v0 v0.9.1
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/fatih/color v1.7.0
go: extracting k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
go: extracting github.com/google/gofuzz v1.0.0
go: downloading golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
go: extracting github.com/fatih/color v1.7.0
go: extracting k8s.io/klog v1.0.0
go: downloading github.com/mattn/go-colorable v0.1.2
go: downloading github.com/mattn/go-isatty v0.0.8
go: extracting github.com/mattn/go-isatty v0.0.8
go: downloading golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
go: extracting github.com/mattn/go-colorable v0.1.2
go: extracting golang.org/x/tools v0.0.0-20190920225731-5eefd052ad72
go: extracting k8s.io/api v0.17.0
go: extracting golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
go: extracting golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
go: extracting github.com/gogo/protobuf v1.2.2-0.20190723190241-65acae22fc9d
go: downloading golang.org/x/text v0.3.2
go: extracting golang.org/x/text v0.3.2
go: finding k8s.io/api v0.17.0
go: finding github.com/spf13/cobra v0.0.5
go: finding github.com/fatih/color v1.7.0
go: finding golang.org/x/tools v0.0.0-20190920225731-5eefd052ad72
go: finding k8s.io/apimachinery v0.17.0
go: finding gopkg.in/yaml.v3 v3.0.0-20190905181640-827449938966
go: finding github.com/gobuffalo/flect v0.2.0
go: finding k8s.io/apiextensions-apiserver v0.17.0
go: finding sigs.k8s.io/yaml v1.1.0
go: finding github.com/mattn/go-colorable v0.1.2
go: finding github.com/mattn/go-isatty v0.0.8
go: finding github.com/gogo/protobuf v1.2.2-0.20190723190241-65acae22fc9d
go: finding github.com/spf13/pflag v1.0.5
go: finding gopkg.in/inf.v0 v0.9.1
go: finding github.com/google/gofuzz v1.0.0
go: finding k8s.io/klog v1.0.0
go: finding gopkg.in/yaml.v2 v2.2.4
go: finding k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
go: finding golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
go: finding golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
go: finding golang.org/x/text v0.3.2
/builder/home/go/bin/controller-gen object:headerFile=./hack/boilerplate.go.txt paths="./..."
go fmt ./...
controllers/contour_ingress.go
go vet ./...
go: downloading github.com/onsi/gomega v1.10.1
go: downloading github.com/onsi/ginkgo v1.14.0
go: extracting github.com/onsi/gomega v1.10.1
go: extracting github.com/onsi/ginkgo v1.14.0
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: downloading github.com/nxadm/tail v1.4.4
go: extracting golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: extracting github.com/nxadm/tail v1.4.4
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: extracting gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: extracting github.com/fsnotify/fsnotify v1.4.9
/builder/home/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
rm -rf generated
mkdir generated
kustomize build config/default/ -o generated
cp generated/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml testing/machinelearning.seldon.io_seldondeployments.yaml
ginkgo -r -outputdir=. -cover -coverprofile=cover.out ./controllers ./utils ./apis
[1595047290] [1mController Suite[0m - 37/37 specs test k8s client
&{Reader:0xc00054cb00 Writer:0xc000e94750 StatusClient:0xc000e94750}
[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0m[32m‚Ä¢[0mE0718 04:42:19.780624   27296 reflector.go:309] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Failed to watch *v1.Service: Get http://127.0.0.1:40211/api/v1/services?allowWatchBookmarks=true&resourceVersion=362&timeoutSeconds=414&watch=true: dial tcp 127.0.0.1:40211: connect: connection refused
E0718 04:42:19.780691   27296 reflector.go:309] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Failed to watch *v2beta1.HorizontalPodAutoscaler: Get http://127.0.0.1:40211/apis/autoscaling/v2beta1/horizontalpodautoscalers?allowWatchBookmarks=true&resourceVersion=213&timeoutSeconds=364&watch=true: dial tcp 127.0.0.1:40211: connect: connection refused
E0718 04:42:19.780908   27296 reflector.go:309] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Failed to watch *v1.SeldonDeployment: Get http://127.0.0.1:40211/apis/machinelearning.seldon.io/v1/seldondeployments?allowWatchBookmarks=true&resourceVersion=369&timeoutSeconds=395&watch=true: dial tcp 127.0.0.1:40211: connect: connection refused
E0718 04:42:19.780958   27296 reflector.go:309] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Failed to watch *v1.Namespace: Get http://127.0.0.1:40211/api/v1/namespaces?allowWatchBookmarks=true&resourceVersion=356&timeoutSeconds=387&watch=true: dial tcp 127.0.0.1:40211: connect: connection refused
E0718 04:42:19.781043   27296 reflector.go:309] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Failed to watch *v1.Deployment: Get http://127.0.0.1:40211/apis/apps/v1/deployments?allowWatchBookmarks=true&resourceVersion=364&timeoutSeconds=384&watch=true: dial tcp 127.0.0.1:40211: connect: connection refused
E0718 04:42:19.781804   27296 reflector.go:309] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Failed to watch *v1.ConfigMap: Get http://127.0.0.1:40211/api/v1/configmaps?allowWatchBookmarks=true&resourceVersion=117&timeoutSeconds=440&watch=true: dial tcp 127.0.0.1:40211: connect: connection refused

 [32mSUCCESS![0m 24.187812112s PASS
coverage: 58.9% of statements
=== RUN   TestGcsSecret
--- PASS: TestGcsSecret (0.00s)
PASS
coverage: 100.0% of statements
=== RUN   TestS3Secret
--- PASS: TestS3Secret (0.00s)
PASS
coverage: 94.6% of statements
=== RUN   TestGetEnvAsBool
--- PASS: TestGetEnvAsBool (0.00s)
PASS
coverage: 10.9% of statements
=== RUN   TestGenerateCerts
--- PASS: TestGenerateCerts (5.09s)
=== RUN   TestConfigmapCreate
--- PASS: TestConfigmapCreate (0.00s)
=== RUN   TestCRDCreate
--- PASS: TestCRDCreate (0.06s)
=== RUN   TestMutatingWebhookCreate
--- PASS: TestMutatingWebhookCreate (4.61s)
=== RUN   TestMutatingWebhookCreateNamespaced
--- PASS: TestMutatingWebhookCreateNamespaced (2.14s)
=== RUN   TestValidatingWebhookCreate
--- PASS: TestValidatingWebhookCreate (1.64s)
=== RUN   TestValidatingWebhookCreateNamespaced
--- PASS: TestValidatingWebhookCreateNamespaced (5.77s)
=== RUN   TestWebHookSvcCreate
--- PASS: TestWebHookSvcCreate (0.47s)
PASS
coverage: 52.1% of statements
=== RUN   TestImageSetNormal
--- PASS: TestImageSetNormal (0.00s)
    prepack_test.go:50: Scenario: GRPC image with version
    prepack_test.go:50: Scenario: GRPC image with no version
    prepack_test.go:50: Scenario: REST image with version
    prepack_test.go:50: Scenario: REST image with no version
=== RUN   TestGetPredictorConfig
--- PASS: TestGetPredictorConfig (0.00s)
    prepack_test.go:81: Scenario: default image sklearn
    prepack_test.go:81: Scenario: related image sklearn
=== RUN   TestGetDeploymentNameOneModel
--- PASS: TestGetDeploymentNameOneModel (0.00s)
=== RUN   TestGetDeploymentNameLong
--- PASS: TestGetDeploymentNameLong (0.00s)
=== RUN   TestValidateBadProtocol
--- PASS: TestValidateBadProtocol (0.00s)
=== RUN   TestValidateBadTransport
--- PASS: TestValidateBadTransport (0.00s)
=== RUN   TestValidateMixedTransport
--- PASS: TestValidateMixedTransport (0.00s)
=== RUN   TestValidateMixedMultipleTransport
--- PASS: TestValidateMixedMultipleTransport (0.00s)
=== RUN   TestDefaultSingleContainer
--- PASS: TestDefaultSingleContainer (0.00s)
=== RUN   TestMetricsPortAddedTwoContainers
--- PASS: TestMetricsPortAddedTwoContainers (0.00s)
=== RUN   TestMetricsPortAddedTwoComponentSpecsTwoContainers
--- PASS: TestMetricsPortAddedTwoComponentSpecsTwoContainers (0.00s)
=== RUN   TestOverrideMetricsPortName
Failed to find config map seldon-config
no kind is registered for the type v1.ConfigMap in scheme "pkg/runtime/scheme.go:101"
--- PASS: TestOverrideMetricsPortName (0.00s)
=== RUN   TestPortUseExisting
--- PASS: TestPortUseExisting (0.00s)
=== RUN   TestMetricsPortAddedToPrepacked
--- PASS: TestMetricsPortAddedToPrepacked (0.00s)
=== RUN   TestPredictorProtocolGrpc
--- PASS: TestPredictorProtocolGrpc (0.00s)
=== RUN   TestPrepackedWithExistingContainer
--- PASS: TestPrepackedWithExistingContainer (0.00s)
=== RUN   TestPrepackedWithCustom
--- PASS: TestPrepackedWithCustom (0.00s)
=== RUN   TestPrepackedWithExistingContainerAndImage
--- PASS: TestPrepackedWithExistingContainerAndImage (0.00s)
=== RUN   TestMetricsPortAddedToTwoPrepacked
--- PASS: TestMetricsPortAddedToTwoPrepacked (0.00s)
=== RUN   TestDefaultPrepackagedServerType
--- PASS: TestDefaultPrepackagedServerType (0.00s)
=== RUN   TestValidateSingleModel
--- PASS: TestValidateSingleModel (0.00s)
=== RUN   TestValidateSingleModelNoName
--- PASS: TestValidateSingleModelNoName (0.00s)
=== RUN   TestValidateNoEngineMultiGraph
--- PASS: TestValidateNoEngineMultiGraph (0.00s)
=== RUN   TestValidateDuplPredictorName
--- PASS: TestValidateDuplPredictorName (0.00s)
=== RUN   TestValidateTrafficSum
--- PASS: TestValidateTrafficSum (0.00s)
=== RUN   TestDefaultABTest
--- PASS: TestDefaultABTest (0.00s)
=== RUN   TestValidateTensorflowProtocolNormalPrepackaged
--- PASS: TestValidateTensorflowProtocolNormalPrepackaged (0.01s)
=== RUN   TestValidateTensorflowProtocolNormal
--- PASS: TestValidateTensorflowProtocolNormal (0.00s)
=== RUN   TestPredictorNoGraph
--- PASS: TestPredictorNoGraph (0.00s)
PASS
coverage: 41.6% of statements
path is /workspace/source/operator
All profiles combined

Ginkgo ran 6 suites in 1m9.086794434s
Test Suite Passed
docker build . -t seldonio/seldon-core-operator:1.2.2-dev
Sending build context to Docker daemon  7.664MB
Step 1/22 : FROM golang:1.13.2 as builder
1.13.2: Pulling from library/golang
c7b7d16361e0: Pulling fs layer
b7a128769df1: Pulling fs layer
1128949d0793: Pulling fs layer
667692510b70: Pulling fs layer
c70d80036479: Pulling fs layer
a8669f8c1a42: Pulling fs layer
433331673060: Pulling fs layer
c70d80036479: Waiting
a8669f8c1a42: Waiting
667692510b70: Waiting
b7a128769df1: Verifying Checksum
b7a128769df1: Download complete
1128949d0793: Verifying Checksum
1128949d0793: Download complete
c7b7d16361e0: Verifying Checksum
c7b7d16361e0: Download complete
667692510b70: Verifying Checksum
667692510b70: Download complete
c70d80036479: Verifying Checksum
c70d80036479: Download complete
433331673060: Download complete
a8669f8c1a42: Verifying Checksum
a8669f8c1a42: Download complete
c7b7d16361e0: Pull complete
b7a128769df1: Pull complete
1128949d0793: Pull complete
667692510b70: Pull complete
c70d80036479: Pull complete
a8669f8c1a42: Pull complete
433331673060: Pull complete
Digest: sha256:b3086f21bfbe896973dd6147b46f2736a7deb2c04ed76219835befa0244a9562
Status: Downloaded newer image for golang:1.13.2
 ---> e37698ff7351
Step 2/22 : WORKDIR /workspace
 ---> Running in 4457a61415a0
Removing intermediate container 4457a61415a0
 ---> 596a51a3a5e9
Step 3/22 : COPY go.mod go.mod
 ---> ea456df632d0
Step 4/22 : COPY go.sum go.sum
 ---> c6f02bdb3401
Step 5/22 : RUN go mod download
 ---> Running in 1283ab754271
[91mgo: finding cloud.google.com/go v0.38.0
[0m[91mgo: finding github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
[0m[91mgo: finding github.com/Azure/go-autorest v14.2.0+incompatible
[0m[91mgo: finding github.com/Azure/go-autorest/autorest v0.9.0
[0m[91mgo: finding github.com/Azure/go-autorest/autorest/adal v0.9.0
[0m[91mgo: finding github.com/Azure/go-autorest/autorest/date v0.3.0
[0m[91mgo: finding github.com/Azure/go-autorest/autorest/mocks v0.4.0
[0m[91mgo: finding github.com/Azure/go-autorest/logger v0.1.0
[0m[91mgo: finding github.com/Azure/go-autorest/tracing v0.6.0
[0m[91mgo: finding github.com/BurntSushi/toml v0.3.1
[0m[91mgo: finding github.com/BurntSushi/xgb v0.0.0-20160522181843-27f122750802
[0m[91mgo: finding github.com/NYTimes/gziphandler v0.0.0-20170623195520-56545f4a5d46
[0m[91mgo: finding github.com/PuerkitoBio/purell v1.1.1
[0m[91mgo: finding github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
[0m[91mgo: finding github.com/agnivade/levenshtein v1.0.1
[0m[91mgo: finding github.com/ahmetb/gen-crd-api-reference-docs v0.1.5
[0m[91mgo: finding github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
[0m[91mgo: finding github.com/alecthomas/units v0.0.0-20190717042225-c3de453c63f4
[0m[91mgo: finding github.com/andreyvit/diff v0.0.0-20170406064948-c7f18ee00883
[0m[91mgo: finding github.com/armon/consul-api v0.0.0-20180202201655-eb2c6b5be1b6
[0m[91mgo: finding github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a
[0m[91mgo: finding github.com/beorn7/perks v1.0.1
[0m[91mgo: finding github.com/bgentry/speakeasy v0.1.0
[0m[91mgo: finding github.com/blang/semver v3.5.0+incompatible
[0m[91mgo: finding github.com/census-instrumentation/opencensus-proto v0.2.1
[0m[91mgo: finding github.com/client9/misspell v0.3.4
[0m[91mgo: finding github.com/cncf/udpa/go v0.0.0-20200313221541-5f7e5dd04533
[0m[91mgo: finding github.com/cockroachdb/datadriven v0.0.0-20190809214429-80d97fb3cbaa
[0m[91mgo: finding github.com/coreos/bbolt v1.3.1-coreos.6
[0m[91mgo: finding github.com/coreos/etcd v3.3.15+incompatible
[0m[91mgo: finding github.com/coreos/go-etcd v2.0.0+incompatible
[0m[91mgo: finding github.com/coreos/go-oidc v2.1.0+incompatible
[0m[91mgo: finding github.com/coreos/go-semver v0.3.0
[0m[91mgo: finding github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e
[0m[91mgo: finding github.com/coreos/pkg v0.0.0-20180108230652-97fdf19511ea
[0m[91mgo: finding github.com/cpuguy83/go-md2man v1.0.10
[0m[91mgo: finding github.com/creack/pty v1.1.7
[0m[91mgo: finding github.com/davecgh/go-spew v1.1.1
[0m[91mgo: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
[0m[91mgo: finding github.com/docker/docker v0.7.3-0.20190327010347-be7ac8be2ae0
[0m[91mgo: finding github.com/docker/go-units v0.4.0
[0m[91mgo: finding github.com/docker/spdystream v0.0.0-20160310174837-449fdfce4d96
[0m[91mgo: finding github.com/docopt/docopt-go v0.0.0-20180111231733-ee0de3bc6815
[0m[91mgo: finding github.com/dustin/go-humanize v1.0.0
[0m[91mgo: finding github.com/elazarl/goproxy v0.0.0-20170405201442-c4fc26588b6e
[0m[91mgo: finding github.com/emicklei/go-restful v2.9.5+incompatible
[0m[91mgo: finding github.com/envoyproxy/go-control-plane v0.9.5
[0m[91mgo: finding github.com/envoyproxy/protoc-gen-validate v0.1.0
[0m[91mgo: finding github.com/evanphx/json-patch v4.5.0+incompatible
[0m[91mgo: finding github.com/fatih/color v1.7.0
[0m[91mgo: finding github.com/fsnotify/fsnotify v1.4.9
[0m[91mgo: finding github.com/ghodss/yaml v1.0.0
[0m[91mgo: finding github.com/globalsign/mgo v0.0.0-20181015135952-eeefdecb41b8
[0m[91mgo: finding github.com/go-errors/errors v1.0.1
[0m[91mgo: finding github.com/go-kit/kit v0.8.0
[0m[91mgo: finding github.com/go-logfmt/logfmt v0.4.0
[0m[91mgo: finding github.com/go-logr/logr v0.1.0
[0m[91mgo: finding github.com/go-logr/zapr v0.1.0
[0m[91mgo: finding github.com/go-openapi/analysis v0.19.5
[0m[91mgo: finding github.com/go-openapi/errors v0.19.2
[0m[91mgo: finding github.com/go-openapi/jsonpointer v0.19.3
[0m[91mgo: finding github.com/go-openapi/jsonreference v0.19.3
[0m[91mgo: finding github.com/go-openapi/loads v0.19.4
[0m[91mgo: finding github.com/go-openapi/runtime v0.19.4
[0m[91mgo: finding github.com/go-openapi/spec v0.19.5
[0m[91mgo: finding github.com/go-openapi/strfmt v0.19.3
[0m[91mgo: finding github.com/go-openapi/swag v0.19.5
[0m[91mgo: finding github.com/go-openapi/validate v0.19.5
[0m[91mgo: finding github.com/go-stack/stack v1.8.0
[0m[91mgo: finding github.com/gobuffalo/flect v0.1.5
[0m[91mgo: finding github.com/gogo/protobuf v1.3.1
[0m[91mgo: finding github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
[0m[91mgo: finding github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
[0m[91mgo: finding github.com/golang/mock v1.2.0
[0m[91mgo: finding github.com/golang/protobuf v1.4.2
[0m[91mgo: finding github.com/google/btree v1.0.0
[0m[91mgo: finding github.com/google/go-cmp v0.5.0
[0m[91mgo: finding github.com/google/gofuzz v1.0.0
[0m[91mgo: finding github.com/google/martian v2.1.0+incompatible
[0m[91mgo: finding github.com/google/pprof v0.0.0-20181206194817-3ea8567a2e57
[0m[91mgo: finding github.com/google/renameio v0.1.0
[0m[91mgo: finding github.com/google/uuid v1.1.1
[0m[91mgo: finding github.com/googleapis/gax-go/v2 v2.0.4
[0m[91mgo: finding github.com/googleapis/gnostic v0.3.1
[0m[91mgo: finding github.com/gophercloud/gophercloud v0.1.0
[0m[91mgo: finding github.com/gorilla/websocket v1.4.0
[0m[91mgo: finding github.com/gregjones/httpcache v0.0.0-20180305231024-9cad4c3443a7
[0m[91mgo: finding github.com/grpc-ecosystem/go-grpc-middleware v1.0.1-0.20190118093823-f849b5445de4
[0m[91mgo: finding github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
[0m[91mgo: finding github.com/grpc-ecosystem/grpc-gateway v1.9.5
[0m[91mgo: finding github.com/hashicorp/golang-lru v0.5.4
[0m[91mgo: finding github.com/hashicorp/hcl v1.0.0
[0m[91mgo: finding github.com/hpcloud/tail v1.0.0
[0m[91mgo: finding github.com/imdario/mergo v0.3.9
[0m[91mgo: finding github.com/inconshreveable/mousetrap v1.0.0
[0m[91mgo: finding github.com/jonboulle/clockwork v0.1.0
[0m[91mgo: finding github.com/json-iterator/go v1.1.10
[0m[91mgo: finding github.com/jstemmer/go-junit-report v0.0.0-20190106144839-af01ea7f8024
[0m[91mgo: finding github.com/julienschmidt/httprouter v1.2.0
[0m[91mgo: finding github.com/kisielk/errcheck v1.2.0
[0m[91mgo: finding github.com/kisielk/gotool v1.0.0
[0m[91mgo: finding github.com/konsorten/go-windows-terminal-sequences v1.0.2
[0m[91mgo: finding github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
[0m[91mgo: finding github.com/kr/pretty v0.1.0
[0m[91mgo: finding github.com/kr/pty v1.1.5
[0m[91mgo: finding github.com/kr/text v0.1.0
[0m[91mgo: finding github.com/magiconair/properties v1.8.0
[0m[91mgo: finding github.com/mailru/easyjson v0.7.0
[0m[91mgo: finding github.com/mattn/go-colorable v0.1.2
[0m[91mgo: finding github.com/mattn/go-isatty v0.0.8
[0m[91mgo: finding github.com/mattn/go-runewidth v0.0.2
[0m[91mgo: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
[0m[91mgo: finding github.com/mitchellh/go-homedir v1.1.0
[0m[91mgo: finding github.com/mitchellh/mapstructure v1.1.2
[0m[91mgo: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
[0m[91mgo: finding github.com/modern-go/reflect2 v1.0.1
[0m[91mgo: finding github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
[0m[91mgo: finding github.com/mwitkow/go-conntrack v0.0.0-20161129095857-cc309e4a2223
[0m[91mgo: finding github.com/mxk/go-flowrate v0.0.0-20140419014527-cca7078d478f
[0m[91mgo: finding github.com/nxadm/tail v1.4.4
[0m[91mgo: finding github.com/olekukonko/tablewriter v0.0.0-20170122224234-a0225b3f23b5
[0m[91mgo: finding github.com/onsi/ginkgo v1.14.0
[0m[91mgo: finding github.com/onsi/gomega v1.10.1
[0m[91mgo: finding github.com/pborman/uuid v1.2.0
[0m[91mgo: finding github.com/pelletier/go-toml v1.2.0
[0m[91mgo: finding github.com/peterbourgon/diskv v2.0.1+incompatible
[0m[91mgo: finding github.com/pkg/errors v0.8.1
[0m[91mgo: finding github.com/pmezard/go-difflib v1.0.0
[0m[91mgo: finding github.com/pquerna/cachecontrol v0.0.0-20171018203845-0dec1b30a021
[0m[91mgo: finding github.com/projectcontour/contour v1.4.0
[0m[91mgo: finding github.com/prometheus/client_golang v1.1.0
[0m[91mgo: finding github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
[0m[91mgo: finding github.com/prometheus/common v0.6.0
[0m[91mgo: finding github.com/prometheus/procfs v0.0.11
[0m[91mgo: finding github.com/remyoudompheng/bigfft v0.0.0-20170806203942-52369c62f446
[0m[91mgo: finding github.com/rogpeppe/fastuuid v0.0.0-20150106093220-6724a57986af
[0m[91mgo: finding github.com/rogpeppe/go-internal v1.3.0
[0m[91mgo: finding github.com/russross/blackfriday v1.5.2
[0m[91mgo: finding github.com/russross/blackfriday/v2 v2.0.1
[0m[91mgo: finding github.com/sergi/go-diff v1.1.0
[0m[91mgo: finding github.com/shurcooL/sanitized_anchor_name v1.0.0
[0m[91mgo: finding github.com/sirupsen/logrus v1.4.2
[0m[91mgo: finding github.com/soheilhy/cmux v0.1.4
[0m[91mgo: finding github.com/spf13/afero v1.2.2
[0m[91mgo: finding github.com/spf13/cast v1.3.0
[0m[91mgo: finding github.com/spf13/cobra v0.0.5
[0m[91mgo: finding github.com/spf13/jwalterweatherman v1.0.0
[0m[91mgo: finding github.com/spf13/pflag v1.0.5
[0m[91mgo: finding github.com/spf13/viper v1.3.2
[0m[91mgo: finding github.com/stretchr/ob** v0.2.0
[0m[91mgo: finding github.com/stretchr/testify v1.4.0
[0m[91mgo: finding github.com/tidwall/pretty v1.0.0
[0m[91mgo: finding github.com/tmc/grpc-websocket-proxy v0.0.0-20170815181823-89b8d40f7ca8
[0m[91mgo: finding github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8
[0m[91mgo: finding github.com/urfave/cli v1.20.0
[0m[91mgo: finding github.com/vektah/gqlparser v1.1.2
[0m[91mgo: finding github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2
[0m[91mgo: finding github.com/xlab/treeprint v0.0.0-20181112141820-a009c3971eca
[0m[91mgo: finding github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77
[0m[91mgo: finding go.etcd.io/bbolt v1.3.3
[0m[91mgo: finding go.etcd.io/etcd v0.0.0-20191023171146-3cf2f69b5738
[0m[91mgo: finding go.mongodb.org/mongo-driver v1.1.2
[0m[91mgo: finding go.opencensus.io v0.21.0
[0m[91mgo: finding go.uber.org/atomic v1.6.0
[0m[91mgo: finding go.uber.org/multierr v1.5.0
[0m[91mgo: finding go.uber.org/tools v0.0.0-20190618225709-2cfd321de3ee
[0m[91mgo: finding go.uber.org/zap v1.15.0
[0m[91mgo: finding golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
[0m[91mgo: finding golang.org/x/exp v0.0.0-20190312203227-4b39c73a6495
[0m[91mgo: finding golang.org/x/image v0.0.0-20190227222117-0694c2d4d067
[0m[91mgo: finding golang.org/x/lint v0.0.0-20190930215403-16217165b5de
[0m[91mgo: finding golang.org/x/mobile v0.0.0-20190312151609-d3739f865fa6
[0m[91mgo: finding golang.org/x/mod v0.0.0-20190513183733-4bf6d317e70e
[0m[91mgo: finding golang.org/x/net v0.0.0-20200520004742-59133d7f0dd7
[0m[91mgo: finding golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
[0m[91mgo: finding golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e
[0m[91mgo: finding golang.org/x/sys v0.0.0-20200519105757-fe76b779f299
[0m[91mgo: finding golang.org/x/text v0.3.3
[0m[91mgo: finding golang.org/x/time v0.0.0-20190921001708-c4c64cad1fd0
[0m[91mgo: finding golang.org/x/tools v0.0.0-20191029190741-b9c20aec41a5
[0m[91mgo: finding golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
[0m[91mgo: finding gomodules.xyz/jsonpatch/v2 v2.0.1
[0m[91mgo: finding gonum.org/v1/gonum v0.0.0-20190331200053-3d26580ed485
[0m[91mgo: finding gonum.org/v1/netlib v0.0.0-20190331212654-76723241ea4e
[0m[91mgo: finding google.golang.org/api v0.4.0
[0m[91mgo: finding google.golang.org/appengine v1.6.5
[0m[91mgo: finding google.golang.org/genproto v0.0.0-20190916214212-f660b8655731
[0m[91mgo: finding google.golang.org/grpc v1.25.1
[0m[91mgo: finding google.golang.org/protobuf v1.23.0
[0m[91mgo: finding gopkg.in/alecthomas/kingpin.v2 v2.2.6
[0m[91mgo: finding gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15
[0m[91mgo: finding gopkg.in/cheggaaa/pb.v1 v1.0.25
[0m[91mgo: finding gopkg.in/errgo.v2 v2.1.0
[0m[91mgo: finding gopkg.in/fsnotify.v1 v1.4.7
[0m[91mgo: finding gopkg.in/inf.v0 v0.9.1
[0m[91mgo: finding gopkg.in/natefinch/lumberjack.v2 v2.0.0
[0m[91mgo: finding gopkg.in/resty.v1 v1.12.0
[0m[91mgo: finding gopkg.in/square/go-jose.v2 v2.2.2
[0m[91mgo: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
[0m[91mgo: finding gopkg.in/yaml.v2 v2.3.0
[0m[91mgo: finding gopkg.in/yaml.v3 v3.0.0-20191120175047-4206685974f2
[0m[91mgo: finding gotest.tools v2.2.0+incompatible
[0m[91mgo: finding honnef.co/go/tools v0.0.1-2019.2.3
[0m[91mgo: finding istio.io/api v0.0.0-20200513175333-ae3da0d240e3
[0m[91mgo: finding istio.io/client-go v0.0.0-20200513180646-f8d9d8ff84e6
[0m[91mgo: finding istio.io/gogo-genproto v0.0.0-20190930162913-45029607206a
[0m[91mgo: finding k8s.io/api v0.17.8
[0m[91mgo: finding k8s.io/apiextensions-apiserver v0.17.8
[0m[91mgo: finding k8s.io/apimachinery v0.17.8
[0m[91mgo: finding k8s.io/apiserver v0.17.8
[0m[91mgo: finding k8s.io/client-go v0.17.8
[0m[91mgo: finding k8s.io/code-generator v0.17.8
[0m[91mgo: finding k8s.io/component-base v0.17.8
[0m[91mgo: finding k8s.io/gengo v0.0.0-20191120174120-e74f70b9b27e
[0m[91mgo: finding k8s.io/klog v1.0.0
[0m[91mgo: finding k8s.io/klog/v2 v2.0.0
[0m[91mgo: finding k8s.io/kube-openapi v0.0.0-20200410145947-bcb3869e6f29
[0m[91mgo: finding k8s.io/utils v0.0.0-20200619165400-6e3d28b6ed19
[0m[91mgo: finding knative.dev/pkg v0.0.0-20200513151758-7b6bb61326ae
[0m[91mgo: finding modernc.org/cc v1.0.0
[0m[91mgo: finding modernc.org/golex v1.0.0
[0m[91mgo: finding modernc.org/mathutil v1.0.0
[0m[91mgo: finding modernc.org/strutil v1.0.0
[0m[91mgo: finding modernc.org/xc v1.0.0
[0m[91mgo: finding sigs.k8s.io/controller-runtime v0.5.8
[0m[91mgo: finding sigs.k8s.io/controller-tools v0.2.4
[0m[91mgo: finding sigs.k8s.io/kustomize/kyaml v0.1.1
[0m[91mgo: finding sigs.k8s.io/service-apis v0.0.0-20200213014236-51691dd89266
[0m[91mgo: finding sigs.k8s.io/structured-merge-diff v0.0.0-20190817042607-6149e4549fca
[0m[91mgo: finding sigs.k8s.io/structured-merge-diff/v2 v2.0.1
[0m[91mgo: finding sigs.k8s.io/testing_frameworks v0.1.2
[0m[91mgo: finding sigs.k8s.io/yaml v1.1.0
[0mRemoving intermediate container 1283ab754271
 ---> 6a1b2c92584c
Step 6/22 : COPY main.go main.go
 ---> cf3ff6cd2cb1
Step 7/22 : COPY apis/ apis/
 ---> d7ac0a46be86
Step 8/22 : COPY controllers/ controllers/
 ---> facb348379c7
Step 9/22 : COPY utils/ utils/
 ---> b639e5aef434
Step 10/22 : COPY constants/ constants/
 ---> 2b0f5ab832aa
Step 11/22 : COPY client/ client/
 ---> a25d1a189c23
Step 12/22 : RUN go build -a -o manager main.go
 ---> Running in f8e703881bac
Removing intermediate container f8e703881bac
 ---> fb48f6c22e73
Step 13/22 : FROM gcr.io/distroless/base:latest
latest: Pulling from distroless/base
24f0c933cbef: Pulling fs layer
69e2f037cdb3: Pulling fs layer
24f0c933cbef: Verifying Checksum
69e2f037cdb3: Verifying Checksum
69e2f037cdb3: Download complete
24f0c933cbef: Pull complete
69e2f037cdb3: Pull complete
Digest: sha256:2b0a8e9a13dcc168b126778d9e947a7081b4d2ee1ee122830d835f176d0e2a70
Status: Downloaded newer image for gcr.io/distroless/base:latest
 ---> c4c70323b0c2
Step 14/22 : WORKDIR /
 ---> Running in 8706c1fd67ec
Removing intermediate container 8706c1fd67ec
 ---> cfb1a1cc65f3
Step 15/22 : COPY --from=builder /workspace/manager .
 ---> a073643dadf5
Step 16/22 : COPY licenses/license.txt licenses/license.txt
 ---> 24e28d3224df
Step 17/22 : COPY generated/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_seldon-mutating-webhook-configuration.yaml /tmp/operator-resources/mutate.yaml
 ---> 7f810cf25ef3
Step 18/22 : COPY generated/admissionregistration.k8s.io_v1beta1_validatingwebhookconfiguration_seldon-validating-webhook-configuration.yaml /tmp/operator-resources/validate.yaml
 ---> b8b556feab43
Step 19/22 : COPY generated/~g_v1_service_seldon-webhook-service.yaml /tmp/operator-resources/service.yaml
 ---> 6a03da9d54cc
Step 20/22 : COPY generated/~g_v1_configmap_seldon-config.yaml /tmp/operator-resources/configmap.yaml
 ---> b06c62a4b711
Step 21/22 : COPY generated/apiextensions.k8s.io_v1beta1_customresourcedefinition_seldondeployments.machinelearning.seldon.io.yaml /tmp/operator-resources/crd.yaml
 ---> ee3b28eebb1b
Step 22/22 : ENTRYPOINT ["/manager"]
 ---> Running in 94e47a179a2c
Removing intermediate container 94e47a179a2c
 ---> 68882b3bd0d2
Successfully built 68882b3bd0d2
Successfully tagged seldonio/seldon-core-operator:1.2.2-dev
docker save seldonio/seldon-core-operator:1.2.2-dev > operator.tar
kind load image-archive operator.tar --name kind
make[1]: Leaving directory '/workspace/source/operator'
Files changed in engine folder:
SKIPPING ENGINE IMAGE BUILD...
Files changed in executor folder:
SKIPPING EXECUTOR IMAGE BUILD...
Build test models
make -C ../docker/fixed-model kind_load_images
make[1]: Entering directory '/workspace/source/testing/docker/fixed-model'
s2i build -E environment_rest_v1 . seldonio/seldon-core-s2i-python3:0.15 seldonio/fixed-model:0.1
---> Installing application source...
Build completed successfully
s2i build -E environment_rest_v2 . seldonio/seldon-core-s2i-python3:0.15 seldonio/fixed-model:0.2
---> Installing application source...
Build completed successfully
kind load -v 3 docker-image seldonio/fixed-model:0.1
Image: "seldonio/fixed-model:0.1" with ID "sha256:4bbbb73391754c8418decd06da593bf0f776f1ae81899be21b6b583854f0cea9" not present on node "kind-control-plane"
Image: "seldonio/fixed-model:0.1" with ID "sha256:4bbbb73391754c8418decd06da593bf0f776f1ae81899be21b6b583854f0cea9" not present on node "kind-worker"
kind load -v 3 docker-image seldonio/fixed-model:0.2
Image: "seldonio/fixed-model:0.2" with ID "sha256:8229d73d9504ebdc0b67139d137be1f1be78cc1312b734920d86e33e49a36464" not present on node "kind-control-plane"
Image: "seldonio/fixed-model:0.2" with ID "sha256:8229d73d9504ebdc0b67139d137be1f1be78cc1312b734920d86e33e49a36464" not present on node "kind-worker"
make[1]: Leaving directory '/workspace/source/testing/docker/fixed-model'
make -C ../docker/echo-model kind_load_image
make[1]: Entering directory '/workspace/source/testing/docker/echo-model'
s2i build \
	-E environment_rest \
	.\
	seldonio/seldon-core-s2i-python3:1.1.1-SNAPSHOT\
	seldonio/echo-model:0.1
---> Installing application source...
Build completed successfully
kind load -v 3 docker-image seldonio/echo-model:0.1
Image: "seldonio/echo-model:0.1" with ID "sha256:e48c48894bc44afd63a1088b6ce36ae104368467c26af87fcf1ff59aa399d1d7" not present on node "kind-control-plane"
Image: "seldonio/echo-model:0.1" with ID "sha256:e48c48894bc44afd63a1088b6ce36ae104368467c26af87fcf1ff59aa399d1d7" not present on node "kind-worker"
make[1]: Leaving directory '/workspace/source/testing/docker/echo-model'
Files changed in prepackaged folder:
SKIPPING PREPACKAGED IMAGE BUILD...
Files changed in alibi folder:
SKIPPING ALIBI IMAGE BUILD...
Files changed in misc folders:
SKIPPING MISC IMAGE BUILD...
kubectl create namespace seldon || echo "Namespace seldon already exists"
namespace/seldon created
kubectl create namespace test1 || echo "Namespace test1 already exists"
namespace/test1 created
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
"stable" has been added to your repositories
helm repo add seldonio https://storage.googleapis.com/seldon-charts
"seldonio" has been added to your repositories
helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
"jaegertracing" has been added to your repositories
helm repo add datawire https://www.getambassador.io
"datawire" has been added to your repositories
helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "seldonio" chart repository
...Successfully got an update from the "jaegertracing" chart repository
...Successfully got an update from the "datawire" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ‚éà Happy Helming!‚éà 
helm install ambassador \
	datawire/ambassador \
	-f ../resources/ambassador_values.yaml \
	--set image.repository=quay.io/datawire/ambassador \
	--set crds.keep=false \
	--set enableAES=false \
	--namespace seldon \
	--set replicaCount=1 \
	--wait
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
NAME: ambassador
LAST DEPLOYED: Sat Jul 18 04:50:10 2020
NAMESPACE: seldon
STATUS: deployed
REVISION: 1
NOTES:
-------------------------------------------------------------------------------
  Congratulations! You've successfully installed Ambassador!

-------------------------------------------------------------------------------
To get the IP address of Ambassador, run the following commands:
  export NODE_PORT=$(kubectl get --namespace seldon -o jsonpath="{.spec.ports[0].nodePort}" services ambassador)
  export NODE_IP=$(kubectl get nodes --namespace seldon -o jsonpath="{.items[0].status.addresses[0].address}")
  echo http://$NODE_IP:$NODE_PORT

For help, visit our Slack at https://d6e.co/slack or view the documentation online at https://www.getambassador.io.
kubectl apply -f istio-1.4.2.yaml
clusterrole.rbac.authorization.k8s.io/istio-reader-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-reader-istio-system created
customresourcedefinition.apiextensions.k8s.io/attributemanifests.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/clusterrbacconfigs.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/destinationrules.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/envoyfilters.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/gateways.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/httpapispecbindings.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/httpapispecs.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/meshpolicies.authentication.istio.io created
customresourcedefinition.apiextensions.k8s.io/policies.authentication.istio.io created
customresourcedefinition.apiextensions.k8s.io/quotaspecbindings.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/quotaspecs.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/rbacconfigs.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/rules.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/serviceentries.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/servicerolebindings.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/serviceroles.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/virtualservices.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/adapters.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/instances.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/templates.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/handlers.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/sidecars.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/authorizationpolicies.security.istio.io created
namespace/istio-system created
serviceaccount/istio-reader-service-account created
clusterrole.rbac.authorization.k8s.io/istio-citadel-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-citadel-istio-system created
deployment.apps/istio-citadel created
poddisruptionbudget.policy/istio-citadel created
service/istio-citadel created
serviceaccount/istio-citadel-service-account created
deployment.apps/istio-egressgateway created
poddisruptionbudget.policy/istio-egressgateway created
gateway.networking.istio.io/istio-multicluster-egressgateway created
virtualservice.networking.istio.io/istio-multicluster-egressgateway created
envoyfilter.networking.istio.io/istio-multicluster-egressgateway created
destinationrule.networking.istio.io/istio-multicluster-destinationrule created
service/istio-egressgateway created
role.rbac.authorization.k8s.io/istio-egressgateway-sds created
rolebinding.rbac.authorization.k8s.io/istio-egressgateway-sds created
serviceaccount/istio-egressgateway-service-account created
clusterrole.rbac.authorization.k8s.io/istio-galley-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-galley-*****-role-binding-istio-system created
configmap/istio-mesh-galley created
configmap/istio-galley-configuration created
deployment.apps/istio-galley created
poddisruptionbudget.policy/istio-galley created
service/istio-galley created
serviceaccount/istio-galley-service-account created
configmap/istio-grafana-configuration-dashboards-citadel-dashboard created
configmap/istio-grafana-configuration-dashboards-galley-dashboard created
configmap/istio-grafana-configuration-dashboards-istio-mesh-dashboard created
configmap/istio-grafana-configuration-dashboards-istio-performance-dashboard created
configmap/istio-grafana-configuration-dashboards-istio-service-dashboard created
configmap/istio-grafana-configuration-dashboards-istio-workload-dashboard created
configmap/istio-grafana-configuration-dashboards-mixer-dashboard created
configmap/istio-grafana-configuration-dashboards-pilot-dashboard created
configmap/istio-grafana created
deployment.apps/grafana created
policy.authentication.istio.io/grafana-ports-mtls-disabled created
service/grafana created
deployment.apps/istio-ingressgateway created
gateway.networking.istio.io/ingressgateway created
poddisruptionbudget.policy/ingressgateway created
service/istio-ingressgateway created
serviceaccount/istio-ingressgateway-service-account created
sidecar.networking.istio.io/default created
clusterrole.rbac.authorization.k8s.io/istio-sidecar-injector-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-sidecar-injector-*****-role-binding-istio-system created
configmap/injector-mesh created
deployment.apps/istio-sidecar-injector created
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector created
poddisruptionbudget.policy/istio-sidecar-injector created
service/istio-sidecar-injector created
serviceaccount/istio-sidecar-injector-service-account created
configmap/istio-sidecar-injector created
clusterrole.rbac.authorization.k8s.io/kiali created
clusterrole.rbac.authorization.k8s.io/kiali-viewer created
clusterrolebinding.rbac.authorization.k8s.io/kiali created
configmap/kiali created
secret/kiali created
deployment.apps/kiali created
service/kiali created
serviceaccount/kiali-service-account created
clusterrole.rbac.authorization.k8s.io/istio-pilot-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-pilot-istio-system created
configmap/pilot-envoy-config created
configmap/istio created
deployment.apps/istio-pilot created
meshpolicy.authentication.istio.io/default created
poddisruptionbudget.policy/istio-pilot created
service/istio-pilot created
serviceaccount/istio-pilot-service-account created
clusterrole.rbac.authorization.k8s.io/istio-policy created
clusterrolebinding.rbac.authorization.k8s.io/istio-policy-*****-role-binding-istio-system created
destinationrule.networking.istio.io/istio-policy created
deployment.apps/istio-policy created
poddisruptionbudget.policy/istio-policy created
service/istio-policy created
serviceaccount/istio-policy-service-account created
clusterrole.rbac.authorization.k8s.io/prometheus-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-istio-system created
configmap/prometheus created
deployment.apps/prometheus created
service/prometheus created
serviceaccount/prometheus created
horizontalpodautoscaler.autoscaling/istio-telemetry created
clusterrole.rbac.authorization.k8s.io/istio-mixer-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-mixer-*****-role-binding-istio-system created
attributemanifest.config.istio.io/istioproxy created
attributemanifest.config.istio.io/kubernetes created
handler.config.istio.io/stdio created
instance.config.istio.io/accesslog created
instance.config.istio.io/tcpaccesslog created
rule.config.istio.io/stdio created
rule.config.istio.io/stdiotcp created
instance.config.istio.io/requestcount created
instance.config.istio.io/requestduration created
instance.config.istio.io/requestsize created
instance.config.istio.io/responsesize created
instance.config.istio.io/tcpbytesent created
instance.config.istio.io/tcpbytereceived created
instance.config.istio.io/tcpconnectionsopened created
instance.config.istio.io/tcpconnectionsclosed created
handler.config.istio.io/prometheus created
rule.config.istio.io/promhttp created
rule.config.istio.io/promtcp created
rule.config.istio.io/promtcpconnectionopen created
rule.config.istio.io/promtcpconnectionclosed created
handler.config.istio.io/kubernetesenv created
rule.config.istio.io/kubeattrgenrulerule created
rule.config.istio.io/tcpkubeattrgenrulerule created
instance.config.istio.io/attributes created
destinationrule.networking.istio.io/istio-telemetry created
configmap/telemetry-envoy-config created
deployment.apps/istio-telemetry created
poddisruptionbudget.policy/istio-telemetry created
service/istio-telemetry created
serviceaccount/istio-mixer-service-account created
deployment.apps/istio-tracing created
service/jaeger-query created
service/jaeger-collector created
service/jaeger-agent created
service/zipkin created
service/tracing created
kubectl rollout status deployment.apps/istio-ingressgateway -n istio-system
Waiting for deployment "istio-ingressgateway" rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for deployment "istio-ingressgateway" rollout to finish: 0 of 1 updated replicas are available...
deployment "istio-ingressgateway" successfully rolled out
kubectl rollout status deployment.apps/istio-pilot -n istio-system
deployment "istio-pilot" successfully rolled out
kubectl rollout status deployment.apps/istio-citadel -n istio-system
deployment "istio-citadel" successfully rolled out
kubectl create -f ../resources/seldon-gateway.yaml -n istio-system
gateway.networking.istio.io/seldon-gateway created
kubectl apply -f ../resources/contour_nodeport.yaml
namespace/projectcontour created
serviceaccount/contour created
serviceaccount/envoy created
configmap/contour created
customresourcedefinition.apiextensions.k8s.io/httpproxies.projectcontour.io created
customresourcedefinition.apiextensions.k8s.io/tlscertificatedelegations.projectcontour.io created
serviceaccount/contour-certgen created
rolebinding.rbac.authorization.k8s.io/contour created
role.rbac.authorization.k8s.io/contour-certgen created
job.batch/contour-certgen-v1.6.0 created
clusterrolebinding.rbac.authorization.k8s.io/contour created
clusterrole.rbac.authorization.k8s.io/contour created
role.rbac.authorization.k8s.io/contour-leaderelection created
rolebinding.rbac.authorization.k8s.io/contour-leaderelection created
service/contour created
service/envoy created
deployment.apps/contour created
daemonset.apps/envoy created
helm install jaeger-operator \
	jaegertracing/jaeger-operator \
	--set rbac.clusterRole=true \
	--namespace seldon \
	--wait
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
NAME: jaeger-operator
LAST DEPLOYED: Sat Jul 18 04:52:31 2020
NAMESPACE: seldon
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
jaeger-operator is installed.


Check the jaeger-operator logs
  export POD=$(kubectl get pods-l app.kubernetes.io/instance=jaeger-operator -lapp.kubernetes.io/name=jaeger-operator --namespace seldon --output name)
  kubectl logs $POD --namespace=seldon
kubectl apply -f ../resources/jaeger.yaml --namespace seldon
jaeger.jaegertracing.io/jaeger created
mapping.getambassador.io/jaeger created
cd ../../operator && make install-cert-manager
make[1]: Entering directory '/workspace/source/operator'
kubectl create namespace cert-manager || echo "Namespace cert-manager-exists"
namespace/cert-manager created
kubectl label namespace cert-manager cert-manager.io/disable-validation=true || echo "namespace cert-manager-already labelled"
namespace/cert-manager labeled
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.12.0/cert-manager.yaml
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io created
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
namespace/cert-manager configured
serviceaccount/cert-manager-cainjector created
serviceaccount/cert-manager created
serviceaccount/cert-manager-webhook created
clusterrole.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-cainjector created
role.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
rolebinding.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:auth-delegator created
rolebinding.rbac.authorization.k8s.io/cert-manager-webhook:webhook-authentication-reader created
clusterrole.rbac.authorization.k8s.io/cert-manager-webhook:webhook-requester created
role.rbac.authorization.k8s.io/cert-manager:leaderelection created
rolebinding.rbac.authorization.k8s.io/cert-manager:leaderelection created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrole.rbac.authorization.k8s.io/cert-manager-view created
clusterrole.rbac.authorization.k8s.io/cert-manager-edit created
service/cert-manager created
service/cert-manager-webhook created
deployment.apps/cert-manager-cainjector created
deployment.apps/cert-manager created
deployment.apps/cert-manager-webhook created
mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
kubectl rollout status deployment.apps/cert-manager -n cert-manager
Waiting for deployment "cert-manager" rollout to finish: 0 of 1 updated replicas are available...
deployment "cert-manager" successfully rolled out
kubectl rollout status deployment.apps/cert-manager-cainjector -n cert-manager
deployment "cert-manager-cainjector" successfully rolled out
kubectl rollout status deployment.apps/cert-manager-webhook -n cert-manager
Waiting for deployment "cert-manager-webhook" rollout to finish: 0 of 1 updated replicas are available...
deployment "cert-manager-webhook" successfully rolled out
make[1]: Leaving directory '/workspace/source/operator'
sleep 5 #https://github.com/jetstack/cert-manager/issues/2273
kubectl create namespace seldon-system || echo "namespace seldon-system exists"
namespace/seldon-system created
helm install seldon \
	../../helm-charts/seldon-core-operator \
	--namespace seldon-system \
	--set contour.enabled=true \
	--set contour.virtualhost.fqdn=localhost \
	--set istio.enabled=true \
	--set istio.gateway=istio-system/seldon-gateway \
	--set certManager.enabled=false \
	--set executor.enabled="true" \
	--wait
NAME: seldon
LAST DEPLOYED: Sat Jul 18 04:53:25 2020
NAMESPACE: seldon-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
kubectl config set-context $(kubectl config current-context) --namespace=seldon
Context "kind-kind" modified.
kubectl apply -f metrics.yaml
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader created
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator created
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader created
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io created
serviceaccount/metrics-server created
deployment.apps/metrics-server created
service/metrics-server created
clusterrole.rbac.authorization.k8s.io/system:metrics-server created
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server created
make: Entering directory '/workspace/source/python'
pip install -e . -r requirements-dev.txt
Obtaining file:///workspace/source/python
Collecting Flask<2.0.0
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Requirement already satisfied: jsonschema<4.0.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (3.2.0)
Collecting Flask-cors<4.0.0
  Downloading Flask_Cors-3.0.8-py2.py3-none-any.whl (14 kB)
Collecting redis<4.0.0
  Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)
Requirement already satisfied: requests<3.0.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (2.23.0)
Requirement already satisfied: numpy<2.0.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (1.18.4)
Collecting flatbuffers<2.0.0
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: protobuf<4.0.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 8)) (3.11.3)
Requirement already satisfied: grpcio<2.0.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 9)) (1.28.1)
Collecting Flask-OpenTracing<1.2.0,>=1.1.0
  Downloading Flask-OpenTracing-1.1.0.tar.gz (8.2 kB)
Collecting opentracing<2.3.0,>=2.2.0
  Downloading opentracing-2.2.0.tar.gz (47 kB)
Collecting jaeger-client<4.2.0,>=4.1.0
  Downloading jaeger-client-4.1.0.tar.gz (80 kB)
Collecting grpcio-opentracing<1.2.0,>=1.1.4
  Downloading grpcio_opentracing-1.1.4-py3-none-any.whl (14 kB)
Requirement already satisfied: PyYAML<5.4 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 14)) (5.3.1)
Collecting gunicorn<20.1.0,>=19.9.0
  Downloading gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
Collecting minio<6.0.0,>=4.0.9
  Downloading minio-5.0.10-py2.py3-none-any.whl (75 kB)
Collecting azure-storage-blob<3.0.0,>=2.0.1
  Downloading azure_storage_blob-2.1.0-py2.py3-none-any.whl (88 kB)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 18)) (46.3.0)
Collecting google-cloud-storage>=1.16.0
  Downloading google_cloud_storage-1.29.0-py2.py3-none-any.whl (85 kB)
Requirement already satisfied: prometheus_client<0.9.0,>=0.7.1 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 20)) (0.7.1)
Collecting black==19.10b0
  Downloading black-19.10b0-py36-none-any.whl (97 kB)
Collecting flake8==3.8.1
  Downloading flake8-3.8.1-py2.py3-none-any.whl (72 kB)
Collecting mypy<0.783
  Downloading mypy-0.782-cp36-cp36m-manylinux1_x86_64.whl (20.8 MB)
Collecting Pillow==7.2.0
  Downloading Pillow-7.2.0-cp36-cp36m-manylinux1_x86_64.whl (2.2 MB)
Collecting pytest==5.4.2
  Downloading pytest-5.4.2-py3-none-any.whl (247 kB)
Collecting pytest-cov==2.10.0
  Downloading pytest_cov-2.10.0-py2.py3-none-any.whl (19 kB)
Collecting tox<4.0.0
  Downloading tox-3.17.1-py2.py3-none-any.whl (82 kB)
Collecting grpcio-tools==1.30.0
  Downloading grpcio_tools-1.30.0-cp36-cp36m-manylinux2010_x86_64.whl (2.5 MB)
Collecting mypy-protobuf==1.22
  Downloading mypy_protobuf-1.22-py3-none-any.whl (7.5 kB)
Collecting tenacity==6.2.0
  Downloading tenacity-6.2.0-py2.py3-none-any.whl (24 kB)
Collecting coverage==5.2
  Downloading coverage-5.2-cp36-cp36m-manylinux1_x86_64.whl (229 kB)
Collecting pandas==1.0.1
  Downloading pandas-1.0.1-cp36-cp36m-manylinux1_x86_64.whl (10.1 MB)
Collecting pip-licenses==2.2.1
  Downloading pip_licenses-2.2.1-py3-none-any.whl (14 kB)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.6/site-packages (from Flask<2.0.0->-r requirements.txt (line 1)) (2.11.2)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.6/site-packages (from Flask<2.0.0->-r requirements.txt (line 1)) (1.0.1)
Collecting click>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/site-packages (from jsonschema<4.0.0->-r requirements.txt (line 2)) (19.3.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.6/site-packages (from jsonschema<4.0.0->-r requirements.txt (line 2)) (1.6.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.6/site-packages (from jsonschema<4.0.0->-r requirements.txt (line 2)) (0.16.0)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.6/site-packages (from jsonschema<4.0.0->-r requirements.txt (line 2)) (1.14.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->-r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->-r requirements.txt (line 5)) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->-r requirements.txt (line 5)) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->-r requirements.txt (line 5)) (1.25.9)
Collecting threadloop<2,>=1
  Downloading threadloop-1.0.2.tar.gz (4.9 kB)
Collecting thrift
  Downloading thrift-0.13.0.tar.gz (59 kB)
Collecting tornado<6,>=4.3
  Downloading tornado-5.1.1.tar.gz (516 kB)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/site-packages (from minio<6.0.0,>=4.0.9->-r requirements.txt (line 16)) (2020.1)
Collecting configparser
  Downloading configparser-5.0.0-py3-none-any.whl (22 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/site-packages (from minio<6.0.0,>=4.0.9->-r requirements.txt (line 16)) (2.8.1)
Collecting azure-storage-common~=2.1
  Downloading azure_storage_common-2.1.0-py2.py3-none-any.whl (47 kB)
Collecting azure-common>=1.1.5
  Downloading azure_common-1.1.25-py2.py3-none-any.whl (12 kB)
Collecting google-cloud-core<2.0dev,>=1.2.0
  Downloading google_cloud_core-1.3.0-py2.py3-none-any.whl (26 kB)
Collecting google-resumable-media<0.6dev,>=0.5.0
  Downloading google_resumable_media-0.5.1-py2.py3-none-any.whl (38 kB)
Collecting google-auth<2.0dev,>=1.11.0
  Downloading google_auth-1.19.2-py2.py3-none-any.whl (91 kB)
Collecting regex
  Downloading regex-2020.7.14-cp36-cp36m-manylinux2010_x86_64.whl (660 kB)
Collecting pathspec<1,>=0.6
  Downloading pathspec-0.8.0-py2.py3-none-any.whl (28 kB)
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting typed-ast>=1.4.0
  Downloading typed_ast-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (737 kB)
Collecting toml>=0.9.4
  Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting pycodestyle<2.7.0,>=2.6.0a1
  Downloading pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting pyflakes<2.3.0,>=2.2.0
  Downloading pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting mypy-extensions<0.5.0,>=0.4.3
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting typing-extensions>=3.7.4
  Downloading typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.6/site-packages (from pytest==5.4.2->-r requirements-dev.txt (line 6)) (8.2.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/site-packages (from pytest==5.4.2->-r requirements-dev.txt (line 6)) (1.8.1)
Requirement already satisfied: pluggy<1.0,>=0.12 in /usr/local/lib/python3.6/site-packages (from pytest==5.4.2->-r requirements-dev.txt (line 6)) (0.13.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from pytest==5.4.2->-r requirements-dev.txt (line 6)) (0.1.9)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from pytest==5.4.2->-r requirements-dev.txt (line 6)) (20.3)
Collecting virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0
  Downloading virtualenv-20.0.27-py2.py3-none-any.whl (4.9 MB)
Collecting filelock>=3.0.0
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting PTable
  Downloading PTable-0.9.2.tar.gz (31 kB)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from Jinja2>=2.10.1->Flask<2.0.0->-r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema<4.0.0->-r requirements.txt (line 2)) (3.1.0)
Collecting cryptography
  Downloading cryptography-2.9.2-cp35-abi3-manylinux2010_x86_64.whl (2.7 MB)
Collecting google-api-core<2.0.0dev,>=1.16.0
  Downloading google_api_core-1.21.0-py2.py3-none-any.whl (90 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4; python_version >= "3"
  Downloading rsa-4.6-py3-none-any.whl (47 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.1.1-py3-none-any.whl (10 kB)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->pytest==5.4.2->-r requirements-dev.txt (line 6)) (2.4.7)
Collecting importlib-resources>=1.0; python_version < "3.7"
  Downloading importlib_resources-3.0.0-py2.py3-none-any.whl (23 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (399 kB)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Downloading googleapis_common_protos-1.52.0-py2.py3-none-any.whl (100 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Building wheels for collected packages: Flask-OpenTracing, opentracing, jaeger-client, threadloop, thrift, tornado, PTable
  Building wheel for Flask-OpenTracing (setup.py): started
  Building wheel for Flask-OpenTracing (setup.py): finished with status 'done'
  Created wheel for Flask-OpenTracing: filename=Flask_OpenTracing-1.1.0-py3-none-any.whl size=9070 sha256=47927ac3e674fe5336a1e64dfcfd6895bbc24ffe12df266bebfbba2c1964184c
  Stored in directory: /builder/home/.cache/pip/wheels/ad/4b/2d/24ff0da0a0b53c7c77ce59b843bcceaf644c88703241e59615
  Building wheel for opentracing (setup.py): started
  Building wheel for opentracing (setup.py): finished with status 'done'
  Created wheel for opentracing: filename=opentracing-2.2.0-py3-none-any.whl size=49319 sha256=5a064fdfb95c4bb6219372d40ea552fcc9ec873219aa3229fe97dd6936aee771
  Stored in directory: /builder/home/.cache/pip/wheels/39/40/44/8bace79f4514e99786236c31f1df8d1b814ff02c1e08b1d697
  Building wheel for jaeger-client (setup.py): started
  Building wheel for jaeger-client (setup.py): finished with status 'done'
  Created wheel for jaeger-client: filename=jaeger_client-4.1.0-py3-none-any.whl size=64309 sha256=373aa9759a2ab8490426186c13a1591d176da78e4704dcab3a92ec34716f1243
  Stored in directory: /builder/home/.cache/pip/wheels/e9/9b/8c/503d0cc13b39a551c054515683ba1d15b40324c863dc442e66
  Building wheel for threadloop (setup.py): started
  Building wheel for threadloop (setup.py): finished with status 'done'
  Created wheel for threadloop: filename=threadloop-1.0.2-py3-none-any.whl size=3423 sha256=50d55743dd3c47130cefa3ab405b2929994ba72020c1f41527f6ee0d3d1fd399
  Stored in directory: /builder/home/.cache/pip/wheels/02/54/65/9f87de48fe8fcaaee30f279973d946ad55f9df56b93b3e78da
  Building wheel for thrift (setup.py): started
  Building wheel for thrift (setup.py): finished with status 'done'
  Created wheel for thrift: filename=thrift-0.13.0-cp36-cp36m-linux_x86_64.whl size=483901 sha256=d205b8d8f572d53a01f017a48024cc80377307f937c556c29a91c37f534d9e7d
  Stored in directory: /builder/home/.cache/pip/wheels/e0/38/fc/472fe18756b177b42096961f8bd3ff2dc5c5620ac399fce52d
  Building wheel for tornado (setup.py): started
  Building wheel for tornado (setup.py): finished with status 'done'
  Created wheel for tornado: filename=tornado-5.1.1-cp36-cp36m-linux_x86_64.whl size=462648 sha256=b22c33149738ea3146cca2777e73292f0b6defdd65d4356d6713476986a885c2
  Stored in directory: /builder/home/.cache/pip/wheels/64/74/71/e7a0d0eb4fc42cb20a17aec36f8f0b5b8c5e1ec19c701fd34a
  Building wheel for PTable (setup.py): started
  Building wheel for PTable (setup.py): finished with status 'done'
  Created wheel for PTable: filename=PTable-0.9.2-py3-none-any.whl size=22907 sha256=71a2599a26e770e98600ec4b5c3b32a7ec88b6a459820d7a8ce0ea680ec02e55
  Stored in directory: /builder/home/.cache/pip/wheels/f3/65/67/71f473ec87ea4554d1bdfb1b5128cfe1414c2b113b72a1ee8e
Successfully built Flask-OpenTracing opentracing jaeger-client threadloop thrift tornado PTable
ERROR: grpcio-tools 1.30.0 has requirement grpcio>=1.30.0, but you'll have grpcio 1.28.1 which is incompatible.
ERROR: google-api-core 1.21.0 has requirement protobuf>=3.12.0, but you'll have protobuf 3.11.3 which is incompatible.
Installing collected packages: click, itsdangerous, Flask, Flask-cors, redis, flatbuffers, opentracing, Flask-OpenTracing, tornado, threadloop, thrift, jaeger-client, grpcio-opentracing, gunicorn, configparser, minio, azure-common, pycparser, cffi, cryptography, azure-storage-common, azure-storage-blob, googleapis-common-protos, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, google-api-core, google-cloud-core, google-resumable-media, google-cloud-storage, regex, pathspec, appdirs, typed-ast, toml, black, pycodestyle, pyflakes, mccabe, flake8, mypy-extensions, typing-extensions, mypy, Pillow, pytest, coverage, pytest-cov, filelock, importlib-resources, distlib, virtualenv, tox, grpcio-tools, mypy-protobuf, tenacity, pandas, PTable, pip-licenses, seldon-core
  Attempting uninstall: tornado
    Found existing installation: tornado 6.0.4
    Uninstalling tornado-6.0.4:
      Successfully uninstalled tornado-6.0.4
  Attempting uninstall: Pillow
    Found existing installation: Pillow 7.1.2
    Uninstalling Pillow-7.1.2:
      Successfully uninstalled Pillow-7.1.2
  Attempting uninstall: pytest
    Found existing installation: pytest 5.3.1
    Uninstalling pytest-5.3.1:
      Successfully uninstalled pytest-5.3.1
  Attempting uninstall: coverage
    Found existing installation: coverage 4.5.4
    Uninstalling coverage-4.5.4:
      Successfully uninstalled coverage-4.5.4
  Attempting uninstall: pytest-cov
    Found existing installation: pytest-cov 2.8.1
    Uninstalling pytest-cov-2.8.1:
      Successfully uninstalled pytest-cov-2.8.1
  Attempting uninstall: grpcio-tools
    Found existing installation: grpcio-tools 1.28.1
    Uninstalling grpcio-tools-1.28.1:
      Successfully uninstalled grpcio-tools-1.28.1
  Attempting uninstall: tenacity
    Found existing installation: tenacity 6.0.0
    Uninstalling tenacity-6.0.0:
      Successfully uninstalled tenacity-6.0.0
  Attempting uninstall: pandas
    Found existing installation: pandas 1.0.3
    Uninstalling pandas-1.0.3:
      Successfully uninstalled pandas-1.0.3
  Running setup.py develop for seldon-core
Successfully installed Flask-1.1.2 Flask-OpenTracing-1.1.0 Flask-cors-3.0.8 PTable-0.9.2 Pillow-7.2.0 appdirs-1.4.4 azure-common-1.1.25 azure-storage-blob-2.1.0 azure-storage-common-2.1.0 black-19.10b0 cachetools-4.1.1 cffi-1.14.0 click-7.1.2 configparser-5.0.0 coverage-5.2 cryptography-2.9.2 distlib-0.3.1 filelock-3.0.12 flake8-3.8.1 flatbuffers-1.12 google-api-core-1.21.0 google-auth-1.19.2 google-cloud-core-1.3.0 google-cloud-storage-1.29.0 google-resumable-media-0.5.1 googleapis-common-protos-1.52.0 grpcio-opentracing-1.1.4 grpcio-tools-1.30.0 gunicorn-20.0.4 importlib-resources-3.0.0 itsdangerous-1.1.0 jaeger-client-4.1.0 mccabe-0.6.1 minio-5.0.10 mypy-0.782 mypy-extensions-0.4.3 mypy-protobuf-1.22 opentracing-2.2.0 pandas-1.0.1 pathspec-0.8.0 pip-licenses-2.2.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycodestyle-2.6.0 pycparser-2.20 pyflakes-2.2.0 pytest-5.4.2 pytest-cov-2.10.0 redis-3.5.3 regex-2020.7.14 rsa-4.6 seldon-core tenacity-6.2.0 threadloop-1.0.2 thrift-0.13.0 toml-0.10.1 tornado-5.1.1 tox-3.17.1 typed-ast-1.4.1 typing-extensions-3.7.4.2 virtualenv-20.0.27
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
make: Leaving directory '/workspace/source/python'
cp ../../proto/prediction.proto ./proto
cd ../../proto/tensorflow && make create_protos
make[1]: Entering directory '/workspace/source/proto/tensorflow'
./create-protos.sh
Downloading proto files for master
make[1]: Leaving directory '/workspace/source/proto/tensorflow'
cp -vr ../../proto/tensorflow/tensorflow .
'../../proto/tensorflow/tensorflow' -> './tensorflow'
'../../proto/tensorflow/tensorflow/core' -> './tensorflow/core'
'../../proto/tensorflow/tensorflow/core/framework' -> './tensorflow/core/framework'
'../../proto/tensorflow/tensorflow/core/framework/types.proto' -> './tensorflow/core/framework/types.proto'
'../../proto/tensorflow/tensorflow/core/framework/resource_handle.proto' -> './tensorflow/core/framework/resource_handle.proto'
'../../proto/tensorflow/tensorflow/core/framework/tensor_shape.proto' -> './tensorflow/core/framework/tensor_shape.proto'
'../../proto/tensorflow/tensorflow/core/framework/tensor.proto' -> './tensorflow/core/framework/tensor.proto'
python -m grpc.tools.protoc -I. --python_out=. --grpc_python_out=. ./proto/prediction.proto
cd ../../notebooks && make build_protos
make[1]: Entering directory '/workspace/source/notebooks'
cd ../proto/tensorflow && make create_protos
make[2]: Entering directory '/workspace/source/proto/tensorflow'
make[2]: Nothing to be done for 'create_protos'.
make[2]: Leaving directory '/workspace/source/proto/tensorflow'
cp -vr ../proto/tensorflow/tensorflow .
'../proto/tensorflow/tensorflow' -> './tensorflow'
'../proto/tensorflow/tensorflow/core' -> './tensorflow/core'
'../proto/tensorflow/tensorflow/core/framework' -> './tensorflow/core/framework'
'../proto/tensorflow/tensorflow/core/framework/types.proto' -> './tensorflow/core/framework/types.proto'
'../proto/tensorflow/tensorflow/core/framework/resource_handle.proto' -> './tensorflow/core/framework/resource_handle.proto'
'../proto/tensorflow/tensorflow/core/framework/tensor_shape.proto' -> './tensorflow/core/framework/tensor_shape.proto'
'../proto/tensorflow/tensorflow/core/framework/tensor.proto' -> './tensorflow/core/framework/tensor.proto'
cp ../proto/prediction.proto ./proto
python -m grpc.tools.protoc -I. --python_out=. --grpc_python_out=. ./proto/prediction.proto
make[1]: Leaving directory '/workspace/source/notebooks'
cd ../../proto/k8s && make create_protos
make[1]: Entering directory '/workspace/source/proto/k8s'
./create-k8s-protos.sh
Downloading proto files for master
Munging proto file packages
sed -i.bak 's|import "k8s.io/apiextensions-apiserver/|//import "k8s.io/apiextensions-apiserver/|' k8s.io/api/core/v1/generated.proto
rm k8s.io/api/core/v1/generated.proto.bak
make[1]: Leaving directory '/workspace/source/proto/k8s'
pip install -r dev_requirements.txt
Collecting pytest==5.3.1
  Downloading pytest-5.3.1-py3-none-any.whl (233 kB)
Requirement already satisfied: pytest-xdist==1.30.0 in /usr/local/lib/python3.6/site-packages (from -r dev_requirements.txt (line 2)) (1.30.0)
Collecting pytest-cov==2.8.1
  Downloading pytest_cov-2.8.1-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: flaky==3.6.1 in /usr/local/lib/python3.6/site-packages (from -r dev_requirements.txt (line 4)) (3.6.1)
Collecting tenacity==6.0.0
  Downloading tenacity-6.0.0-py2.py3-none-any.whl (24 kB)
Collecting sh==1.13.1
  Downloading sh-1.13.1-py2.py3-none-any.whl (40 kB)
Requirement already satisfied: ipython==7.13.0 in /usr/local/lib/python3.6/site-packages (from -r dev_requirements.txt (line 9)) (7.13.0)
Requirement already satisfied: nbconvert==5.6.1 in /usr/local/lib/python3.6/site-packages (from -r dev_requirements.txt (line 10)) (5.6.1)
Requirement already satisfied: alibi==0.3.2 in /usr/local/lib/python3.6/site-packages (from -r dev_requirements.txt (line 11)) (0.3.2)
Requirement already satisfied: matplotlib==3.1.3 in /usr/local/lib/python3.6/site-packages (from -r dev_requirements.txt (line 12)) (3.1.3)
Requirement already satisfied: tensorflow==1.15.2 in /usr/local/lib/python3.6/site-packages (from -r dev_requirements.txt (line 13)) (1.15.2)
Collecting coverage==4.5.4
  Downloading coverage-4.5.4-cp36-cp36m-manylinux1_x86_64.whl (205 kB)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/site-packages (from pytest==5.3.1->-r dev_requirements.txt (line 1)) (19.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from pytest==5.3.1->-r dev_requirements.txt (line 1)) (20.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from pytest==5.3.1->-r dev_requirements.txt (line 1)) (0.1.9)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/site-packages (from pytest==5.3.1->-r dev_requirements.txt (line 1)) (1.8.1)
Requirement already satisfied: pluggy<1.0,>=0.12 in /usr/local/lib/python3.6/site-packages (from pytest==5.3.1->-r dev_requirements.txt (line 1)) (0.13.1)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.6/site-packages (from pytest==5.3.1->-r dev_requirements.txt (line 1)) (1.6.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.6/site-packages (from pytest==5.3.1->-r dev_requirements.txt (line 1)) (8.2.0)
Requirement already satisfied: execnet>=1.1 in /usr/local/lib/python3.6/site-packages (from pytest-xdist==1.30.0->-r dev_requirements.txt (line 2)) (1.7.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from pytest-xdist==1.30.0->-r dev_requirements.txt (line 2)) (1.14.0)
Requirement already satisfied: pytest-forked in /usr/local/lib/python3.6/site-packages (from pytest-xdist==1.30.0->-r dev_requirements.txt (line 2)) (1.1.3)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/site-packages (from ipython==7.13.0->-r dev_requirements.txt (line 9)) (4.4.2)
Requirement already satisfied: jedi>=0.10 in /usr/local/lib/python3.6/site-packages (from ipython==7.13.0->-r dev_requirements.txt (line 9)) (0.17.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/site-packages (from ipython==7.13.0->-r dev_requirements.txt (line 9)) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.6/site-packages (from ipython==7.13.0->-r dev_requirements.txt (line 9)) (4.3.3)
Requirement already satisfied: pygments in /usr/local/lib/python3.6/site-packages (from ipython==7.13.0->-r dev_requirements.txt (line 9)) (2.6.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.6/site-packages (from ipython==7.13.0->-r dev_requirements.txt (line 9)) (0.1.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.6/site-packages (from ipython==7.13.0->-r dev_requirements.txt (line 9)) (3.0.5)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.6/site-packages (from ipython==7.13.0->-r dev_requirements.txt (line 9)) (46.3.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.6/site-packages (from ipython==7.13.0->-r dev_requirements.txt (line 9)) (4.8.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.6/site-packages (from nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (0.6.0)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.6/site-packages (from nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (0.3)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.6/site-packages (from nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (1.4.2)
Requirement already satisfied: testpath in /usr/local/lib/python3.6/site-packages (from nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (0.4.4)
Requirement already satisfied: bleach in /usr/local/lib/python3.6/site-packages (from nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (3.1.5)
Requirement already satisfied: nbformat>=4.4 in /usr/local/lib/python3.6/site-packages (from nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (5.0.6)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.6/site-packages (from nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (0.8.4)
Requirement already satisfied: jinja2>=2.4 in /usr/local/lib/python3.6/site-packages (from nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (2.11.2)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.6/site-packages (from nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (4.6.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/site-packages (from alibi==0.3.2->-r dev_requirements.txt (line 11)) (0.23.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.6/site-packages (from alibi==0.3.2->-r dev_requirements.txt (line 11)) (4.9.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/site-packages (from alibi==0.3.2->-r dev_requirements.txt (line 11)) (1.0.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/site-packages (from alibi==0.3.2->-r dev_requirements.txt (line 11)) (1.18.4)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.6/site-packages (from alibi==0.3.2->-r dev_requirements.txt (line 11)) (0.17.2)
Requirement already satisfied: spacy in /usr/local/lib/python3.6/site-packages (from alibi==0.3.2->-r dev_requirements.txt (line 11)) (2.2.4)
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from alibi==0.3.2->-r dev_requirements.txt (line 11)) (2.23.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.6/site-packages (from alibi==0.3.2->-r dev_requirements.txt (line 11)) (7.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/site-packages (from matplotlib==3.1.3->-r dev_requirements.txt (line 12)) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/site-packages (from matplotlib==3.1.3->-r dev_requirements.txt (line 12)) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/site-packages (from matplotlib==3.1.3->-r dev_requirements.txt (line 12)) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/site-packages (from matplotlib==3.1.3->-r dev_requirements.txt (line 12)) (0.10.0)
Requirement already satisfied: gast==0.2.2 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (0.2.2)
Requirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (1.12.1)
Requirement already satisfied: tensorflow-estimator==1.15.1 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (1.15.1)
Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (0.8.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (3.2.1)
Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (1.28.1)
Requirement already satisfied: google-pasta>=0.1.6 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (0.2.0)
Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (3.11.3)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (1.1.0)
Requirement already satisfied: keras-applications>=1.0.8 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (1.0.8)
Requirement already satisfied: tensorboard<1.16.0,>=1.15.0 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (1.15.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (0.34.2)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (1.1.2)
Requirement already satisfied: absl-py>=0.7.0 in /usr/local/lib/python3.6/site-packages (from tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (0.9.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest==5.3.1->-r dev_requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: apipkg>=1.4 in /usr/local/lib/python3.6/site-packages (from execnet>=1.1->pytest-xdist==1.30.0->-r dev_requirements.txt (line 2)) (1.5)
Requirement already satisfied: parso>=0.7.0 in /usr/local/lib/python3.6/site-packages (from jedi>=0.10->ipython==7.13.0->-r dev_requirements.txt (line 9)) (0.7.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/site-packages (from traitlets>=4.2->ipython==7.13.0->-r dev_requirements.txt (line 9)) (0.2.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/site-packages (from pexpect; sys_platform != "win32"->ipython==7.13.0->-r dev_requirements.txt (line 9)) (0.6.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.6/site-packages (from bleach->nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (0.5.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.6/site-packages (from nbformat>=4.4->nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (3.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from jinja2>=2.4->nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (1.1.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/site-packages (from scikit-learn->alibi==0.3.2->-r dev_requirements.txt (line 11)) (0.14.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.6/site-packages (from scikit-learn->alibi==0.3.2->-r dev_requirements.txt (line 11)) (2.0.0)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.6/site-packages (from scikit-learn->alibi==0.3.2->-r dev_requirements.txt (line 11)) (1.4.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.6/site-packages (from beautifulsoup4->alibi==0.3.2->-r dev_requirements.txt (line 11)) (2.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/site-packages (from pandas->alibi==0.3.2->-r dev_requirements.txt (line 11)) (2020.1)
Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/lib/python3.6/site-packages (from scikit-image->alibi==0.3.2->-r dev_requirements.txt (line 11)) (2020.5.11)
Requirement already satisfied: networkx>=2.0 in /usr/local/lib/python3.6/site-packages (from scikit-image->alibi==0.3.2->-r dev_requirements.txt (line 11)) (2.4)
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.6/site-packages (from scikit-image->alibi==0.3.2->-r dev_requirements.txt (line 11)) (1.1.1)
Requirement already satisfied: imageio>=2.3.0 in /usr/local/lib/python3.6/site-packages (from scikit-image->alibi==0.3.2->-r dev_requirements.txt (line 11)) (2.8.0)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.6/site-packages (from spacy->alibi==0.3.2->-r dev_requirements.txt (line 11)) (1.0.2)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from spacy->alibi==0.3.2->-r dev_requirements.txt (line 11)) (3.0.2)
Requirement already satisfied: thinc==7.4.0 in /usr/local/lib/python3.6/site-packages (from spacy->alibi==0.3.2->-r dev_requirements.txt (line 11)) (7.4.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.6/site-packages (from spacy->alibi==0.3.2->-r dev_requirements.txt (line 11)) (2.0.3)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /usr/local/lib/python3.6/site-packages (from spacy->alibi==0.3.2->-r dev_requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /usr/local/lib/python3.6/site-packages (from spacy->alibi==0.3.2->-r dev_requirements.txt (line 11)) (1.1.3)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /usr/local/lib/python3.6/site-packages (from spacy->alibi==0.3.2->-r dev_requirements.txt (line 11)) (0.6.0)
Requirement already satisfied: srsly<1.1.0,>=1.0.2 in /usr/local/lib/python3.6/site-packages (from spacy->alibi==0.3.2->-r dev_requirements.txt (line 11)) (1.0.2)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in /usr/local/lib/python3.6/site-packages (from spacy->alibi==0.3.2->-r dev_requirements.txt (line 11)) (0.4.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.6/site-packages (from spacy->alibi==0.3.2->-r dev_requirements.txt (line 11)) (4.46.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->alibi==0.3.2->-r dev_requirements.txt (line 11)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->alibi==0.3.2->-r dev_requirements.txt (line 11)) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->alibi==0.3.2->-r dev_requirements.txt (line 11)) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->alibi==0.3.2->-r dev_requirements.txt (line 11)) (2.9)
Requirement already satisfied: h5py in /usr/local/lib/python3.6/site-packages (from keras-applications>=1.0.8->tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (2.10.0)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.6/site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (1.0.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.2->-r dev_requirements.txt (line 13)) (3.2.2)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert==5.6.1->-r dev_requirements.txt (line 10)) (0.16.0)
Requirement already satisfied: imagecodecs>=2020.2.18 in /usr/local/lib/python3.6/site-packages (from tifffile>=2019.7.26->scikit-image->alibi==0.3.2->-r dev_requirements.txt (line 11)) (2020.2.18)
Installing collected packages: pytest, coverage, pytest-cov, tenacity, sh
  Attempting uninstall: pytest
    Found existing installation: pytest 5.4.2
    Uninstalling pytest-5.4.2:
      Successfully uninstalled pytest-5.4.2
  Attempting uninstall: coverage
    Found existing installation: coverage 5.2
    Uninstalling coverage-5.2:
      Successfully uninstalled coverage-5.2
  Attempting uninstall: pytest-cov
    Found existing installation: pytest-cov 2.10.0
    Uninstalling pytest-cov-2.10.0:
      Successfully uninstalled pytest-cov-2.10.0
  Attempting uninstall: tenacity
    Found existing installation: tenacity 6.2.0
    Uninstalling tenacity-6.2.0:
      Successfully uninstalled tenacity-6.2.0
Successfully installed coverage-4.5.4 pytest-5.3.1 pytest-cov-2.8.1 sh-1.13.1 tenacity-6.0.0
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
pip install -e ../../python
Obtaining file:///workspace/source/python
Requirement already satisfied: Flask<2.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (1.1.2)
Requirement already satisfied: jsonschema<4.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (3.2.0)
Requirement already satisfied: Flask-cors<4.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (3.0.8)
Requirement already satisfied: redis<4.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (3.5.3)
Requirement already satisfied: requests<3.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (2.23.0)
Requirement already satisfied: numpy<2.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (1.18.4)
Requirement already satisfied: flatbuffers<2.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (1.12)
Requirement already satisfied: protobuf<4.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (3.11.3)
Requirement already satisfied: grpcio<2.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (1.28.1)
Requirement already satisfied: Flask-OpenTracing<1.2.0,>=1.1.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (1.1.0)
Requirement already satisfied: opentracing<2.3.0,>=2.2.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (2.2.0)
Requirement already satisfied: jaeger-client<4.2.0,>=4.1.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (4.1.0)
Requirement already satisfied: grpcio-opentracing<1.2.0,>=1.1.4 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (1.1.4)
Requirement already satisfied: PyYAML<5.4 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (5.3.1)
Requirement already satisfied: gunicorn<20.1.0,>=19.9.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (20.0.4)
Requirement already satisfied: minio<6.0.0,>=4.0.9 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (5.0.10)
Requirement already satisfied: azure-storage-blob<3.0.0,>=2.0.1 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (2.1.0)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (46.3.0)
Requirement already satisfied: prometheus_client<0.9.0,>=0.7.1 in /usr/local/lib/python3.6/site-packages (from seldon-core==1.2.2.dev0) (0.7.1)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.6/site-packages (from Flask<2.0.0->seldon-core==1.2.2.dev0) (1.0.1)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.6/site-packages (from Flask<2.0.0->seldon-core==1.2.2.dev0) (7.1.2)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.6/site-packages (from Flask<2.0.0->seldon-core==1.2.2.dev0) (2.11.2)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/site-packages (from Flask<2.0.0->seldon-core==1.2.2.dev0) (1.1.0)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.6/site-packages (from jsonschema<4.0.0->seldon-core==1.2.2.dev0) (1.14.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/site-packages (from jsonschema<4.0.0->seldon-core==1.2.2.dev0) (19.3.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.6/site-packages (from jsonschema<4.0.0->seldon-core==1.2.2.dev0) (1.6.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.6/site-packages (from jsonschema<4.0.0->seldon-core==1.2.2.dev0) (0.16.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->seldon-core==1.2.2.dev0) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->seldon-core==1.2.2.dev0) (2020.4.5.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->seldon-core==1.2.2.dev0) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests<3.0.0->seldon-core==1.2.2.dev0) (2.9)
Requirement already satisfied: thrift in /usr/local/lib/python3.6/site-packages (from jaeger-client<4.2.0,>=4.1.0->seldon-core==1.2.2.dev0) (0.13.0)
Requirement already satisfied: threadloop<2,>=1 in /usr/local/lib/python3.6/site-packages (from jaeger-client<4.2.0,>=4.1.0->seldon-core==1.2.2.dev0) (1.0.2)
Requirement already satisfied: tornado<6,>=4.3 in /usr/local/lib/python3.6/site-packages (from jaeger-client<4.2.0,>=4.1.0->seldon-core==1.2.2.dev0) (5.1.1)
Requirement already satisfied: configparser in /usr/local/lib/python3.6/site-packages (from minio<6.0.0,>=4.0.9->seldon-core==1.2.2.dev0) (5.0.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/site-packages (from minio<6.0.0,>=4.0.9->seldon-core==1.2.2.dev0) (2020.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/site-packages (from minio<6.0.0,>=4.0.9->seldon-core==1.2.2.dev0) (2.8.1)
Requirement already satisfied: azure-common>=1.1.5 in /usr/local/lib/python3.6/site-packages (from azure-storage-blob<3.0.0,>=2.0.1->seldon-core==1.2.2.dev0) (1.1.25)
Requirement already satisfied: azure-storage-common~=2.1 in /usr/local/lib/python3.6/site-packages (from azure-storage-blob<3.0.0,>=2.0.1->seldon-core==1.2.2.dev0) (2.1.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from Jinja2>=2.10.1->Flask<2.0.0->seldon-core==1.2.2.dev0) (1.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema<4.0.0->seldon-core==1.2.2.dev0) (3.1.0)
Requirement already satisfied: cryptography in /usr/local/lib/python3.6/site-packages (from azure-storage-common~=2.1->azure-storage-blob<3.0.0,>=2.0.1->seldon-core==1.2.2.dev0) (2.9.2)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.6/site-packages (from cryptography->azure-storage-common~=2.1->azure-storage-blob<3.0.0,>=2.0.1->seldon-core==1.2.2.dev0) (1.14.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography->azure-storage-common~=2.1->azure-storage-blob<3.0.0,>=2.0.1->seldon-core==1.2.2.dev0) (2.20)
Installing collected packages: seldon-core
  Attempting uninstall: seldon-core
    Found existing installation: seldon-core 1.2.2.dev0
    Uninstalling seldon-core-1.2.2.dev0:
      Successfully uninstalled seldon-core-1.2.2.dev0
  Running setup.py develop for seldon-core
Successfully installed seldon-core
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
# Run the core tests in parallel
pytest \
	--verbose \
	-s \
	-W ignore \
	-n "4" \
	-m "not sequential and not notebooks" 2>&1
============================= test session starts ==============================
platform linux -- Python 3.6.10, pytest-5.3.1, py-1.8.1, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /workspace/source/testing/scripts, inifile: setup.cfg
plugins: cov-2.8.1, xdist-1.30.0, forked-1.1.3, flaky-3.6.1
gw0 I / gw1 I / gw2 I / gw3 I
[gw0] linux Python 3.6.10 cwd: /workspace/source/testing/scripts
[gw1] linux Python 3.6.10 cwd: /workspace/source/testing/scripts
[gw2] linux Python 3.6.10 cwd: /workspace/source/testing/scripts
[gw3] linux Python 3.6.10 cwd: /workspace/source/testing/scripts
[gw0] Python 3.6.10 (default, May 14 2020, 12:39:37)  -- [GCC 8.3.0]
[gw1] Python 3.6.10 (default, May 14 2020, 12:39:37)  -- [GCC 8.3.0]
[gw2] Python 3.6.10 (default, May 14 2020, 12:39:37)  -- [GCC 8.3.0]
[gw3] Python 3.6.10 (default, May 14 2020, 12:39:37)  -- [GCC 8.3.0]
gw0 [39] / gw1 [39] / gw2 [39] / gw3 [39]

scheduling tests via LoadScheduling

test_bad_graphs.py::TestBadGraphs::test_duplicate_predictor_name 
test_api_version.py::test_api_version[machinelearning.seldon.io/v1alpha3] 
test_api_version.py::test_api_version[machinelearning.seldon.io/v1alpha2] 
test_api_version.py::test_api_version[machinelearning.seldon.io/v1] Error from server (SeldonDeployment.machinelearing.seldon.io "dupname" is invalid: [spec.predictors[1]: Invalid value: "mymodel": Duplicate predictor name, spec: Invalid value: "mymodel": Traffic must sum to 100 for multiple predictors]): error when creating "../resources/bad_duplicate_predictor_name.json": admission webhook "v1alpha2.vseldondeployment.kb.io" denied the request: SeldonDeployment.machinelearing.seldon.io "dupname" is invalid: [spec.predictors[1]: Invalid value: "mymodel": Duplicate predictor name, spec: Invalid value: "mymodel": Traffic must sum to 100 for multiple predictors]

[gw3] PASSED test_bad_graphs.py::TestBadGraphs::test_duplicate_predictor_name 
test_helm_charts_clusterwide.py::TestClusterWide::test_single_model Error: uninstall: Release not loaded: mymodel: release: not found

[gw2] PASSED test_api_version.py::test_api_version[machinelearning.seldon.io/v1] Error: uninstall: Release not loaded: mymodel: release: not found

[gw0] PASSED test_api_version.py::test_api_version[machinelearning.seldon.io/v1alpha2] Error: uninstall: Release not loaded: mymodel: release: not found

[gw1] PASSED test_api_version.py::test_api_version[machinelearning.seldon.io/v1alpha3] Error: uninstall: Release not loaded: mymodel: release: not found

[gw3] PASSED test_helm_charts_clusterwide.py::TestClusterWide::test_single_model 
test_batch_processor.py::TestBatchWorker::test_batch_worker 
test_bad_graphs.py::TestBadGraphs::test_model_name_mismatch 
test_bad_graphs.py::TestBadGraphs::test_model_no_graph 
test_helm_charts_clusterwide.py::TestClusterWide::test_mab_model Error from server (SeldonDeployment.machinelearing.seldon.io "namemismatch" is invalid: spec.predictors[0].graph: Invalid value: "complex-model_bad_name": Can't find container for Predictive Unit): error when creating "../resources/bad_name_mismatch.json": admission webhook "v1alpha2.vseldondeployment.kb.io" denied the request: SeldonDeployment.machinelearing.seldon.io "namemismatch" is invalid: spec.predictors[0].graph: Invalid value: "complex-model_bad_name": Can't find container for Predictive Unit

[gw0] PASSED test_bad_graphs.py::TestBadGraphs::test_model_name_mismatch 
test_helm_charts_clusterwide.py::TestClusterWide::test_abtest_model Error from server (SeldonDeployment.machinelearing.seldon.io "test-deployment" is invalid: spec.predictors[0].graph: Invalid value: "": Can't find container for Predictive Unit): error when creating "../resources/bad_no_graph.yaml": admission webhook "v1.vseldondeployment.kb.io" denied the request: SeldonDeployment.machinelearing.seldon.io "test-deployment" is invalid: spec.predictors[0].graph: Invalid value: "": Can't find container for Predictive Unit

[gw1] PASSED test_bad_graphs.py::TestBadGraphs::test_model_no_graph 
test_prepackaged_servers.py::TestPrepack::test_tfserving Error: uninstall: Release not loaded: mymab: release: not found

[gw3] PASSED test_helm_charts_clusterwide.py::TestClusterWide::test_mab_model Error: uninstall: Release not loaded: myabtest: release: not found

[gw0] PASSED test_helm_charts_clusterwide.py::TestClusterWide::test_abtest_model 
test_prepackaged_servers.py::TestPrepack::test_mlflow 
test_local_operators.py::TestLocalOperators::test_namespace_operator 
[gw2] PASSED test_batch_processor.py::TestBatchWorker::test_batch_worker 
test_local_operators.py::TestLocalOperators::test_labelled_operator Error from server (InternalError): error when creating "../resources/model_controller_id.yaml": Internal error occurred: failed calling webhook "v1alpha2.mseldondeployment.kb.io": Post https://seldon-webhook-service.test-labelled-operator.svc:443/mutate-machinelearning-seldon-io-v1alpha2-seldondeployment?timeout=30s: dial tcp 10.107.192.216:443: connect: connection refused

[gw3] PASSED test_local_operators.py::TestLocalOperators::test_namespace_operator 
test_prepackaged_servers.py::TestPrepack::test_openapi_sklearn 
[gw2] PASSED test_local_operators.py::TestLocalOperators::test_labelled_operator 
[gw1] PASSED test_prepackaged_servers.py::TestPrepack::test_tfserving 
test_prepackaged_servers.py::TestPrepack::test_xgboost 
test_prepackaged_servers.py::TestPrepack::test_sklearn 
[gw0] PASSED test_prepackaged_servers.py::TestPrepack::test_mlflow 
test_prepackaged_servers.py::TestPrepack::test_text_alibi_explainer 
[gw3] PASSED test_prepackaged_servers.py::TestPrepack::test_openapi_sklearn 
[gw1] PASSED test_prepackaged_servers.py::TestPrepack::test_xgboost 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph2.json-True-ambas] 
[gw2] PASSED test_prepackaged_servers.py::TestPrepack::test_sklearn 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph2.json-True-istio] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph2.json-True-contour] 
[gw0] PASSED test_prepackaged_servers.py::TestPrepack::test_text_alibi_explainer 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph3.json-True-ambas] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph2.json-True-contour] 
[gw3] PASSED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph2.json-True-ambas] 
[gw1] PASSED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph2.json-True-istio] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph3.json-True-istio] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph3.json-True-contour] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph2.json-True-contour] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph3.json-True-contour] 
[gw2] FAILED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph2.json-True-contour] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph4.json-True-ambas] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph3.json-True-contour] 
[gw1] FAILED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph3.json-True-contour] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph5.json-True-ambas] 
[gw2] PASSED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph4.json-True-ambas] error: timed out waiting for the condition on pods/mymodel-mymodel-0-complex-model-84bbf46968-dzkvx

test_rolling_updates.py::test_rolling_deployment[graph1.json-graph5.json-True-istio] 
[gw0] PASSED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph3.json-True-ambas] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph4.json-True-istio] error: timed out waiting for the condition on pods/mymodel-mymodel-0-complex-model-59d955d7d4-l5fm4

[gw3] PASSED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph3.json-True-istio] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph4.json-True-contour] 
[gw0] PASSED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph4.json-True-istio] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph8.json-True-istio] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph4.json-True-contour] error: timed out waiting for the condition on pods/mymodel-mymodel-0-complex-model-f887cf7c4-j2zfr

[gw0] PASSED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph8.json-True-istio] 
test_rolling_updates.py::test_rolling_deployment[graph7.json-graph8.json-False-ambas] error: timed out waiting for the condition on pods/mymodel-mymodel-0-complex-model-f5d6d4dbb-nlr7h

[gw3] FAILED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph4.json-True-contour] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph8.json-True-contour] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph5.json-True-ambas] 
[gw2] PASSED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph5.json-True-istio] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph8.json-True-ambas] 
[gw0] PASSED test_rolling_updates.py::test_rolling_deployment[graph7.json-graph8.json-False-ambas] 
test_rolling_updates.py::test_rolling_deployment[graph7.json-graph8.json-False-istio] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph8.json-True-contour] 
[gw2] PASSED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph8.json-True-ambas] 
[gw0] PASSED test_rolling_updates.py::test_rolling_deployment[graph7.json-graph8.json-False-istio] 
test_security.py::test_xss_escaping 
test_security.py::test_xss_header 
[gw3] FAILED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph8.json-True-contour] 
[gw2] PASSED test_security.py::test_xss_escaping 
test_rolling_updates.py::test_rolling_deployment[graph7.json-graph8.json-False-contour] 
[gw0] PASSED test_security.py::test_xss_header 
test_tracing.py::test_tracing_rest 
[gw2] PASSED test_tracing.py::test_tracing_rest 
test_rolling_updates.py::test_rolling_deployment[graph7.json-graph8.json-False-contour] error: timed out waiting for the condition on pods/mymodel-mymodel-0-complex-model-f887cf7c4-4r2ws

[gw1] PASSED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph5.json-True-ambas] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph5.json-True-contour] 
[gw3] FAILED test_rolling_updates.py::test_rolling_deployment[graph7.json-graph8.json-False-contour] 
test_rolling_updates.py::test_rolling_deployment[graph1.json-graph5.json-True-contour] 
[gw1] FAILED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph5.json-True-contour] 

=================================== FAILURES ===================================
________ test_rolling_deployment[graph1.json-graph2.json-True-contour] _________
[gw2] linux -- Python 3.6.10 /usr/local/bin/python

namespace = 'test-rolling-deployment-graph1-json-graph2-json-true-contour'
api_gateway = 'localhost:8005', from_deployment = 'graph1.json'
to_deployment = 'graph2.json', change = True

    @pytest.mark.flaky(max_runs=3)
    @with_api_gateways
    @pytest.mark.parametrize(
        "from_deployment,to_deployment,change",
        [
            ("graph1.json", "graph2.json", True),  # New image version
            (
                "graph1.json",
                "graph3.json",
                True,
            ),  # New image version and new name of container
            ("graph1.json", "graph4.json", True),  # New resource request but same image
            ("graph1.json", "graph5.json", True),  # Update with multi-deployment new model
            ("graph1.json", "graph8.json", True),  # From v1alpha2 to v1
            ("graph7.json", "graph8.json", False),  # From v1alpha3 to v1
        ],
    )
    def test_rolling_deployment(
        namespace, api_gateway, from_deployment, to_deployment, change
    ):
        from_file_path = to_resources_path(from_deployment)
        retry_run(f"kubectl apply -f {from_file_path} -n {namespace}")
        wait_for_status("mymodel", namespace)
        wait_for_rollout("mymodel", namespace)
>       assert_model("mymodel", namespace, initial=True, endpoint=api_gateway)

test_rolling_updates.py:229: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

sdep_name = 'mymodel'
namespace = 'test-rolling-deployment-graph1-json-graph2-json-true-contour'
initial = True, endpoint = 'localhost:8005'

    def assert_model(sdep_name, namespace, initial=False, endpoint=API_AMBASSADOR):
        _request = initial_rest_request if initial else rest_request
        r = _request(sdep_name, namespace, endpoint=endpoint)
    
>       assert r is not None
E       AssertionError

seldon_e2e_utils.py:592: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
________ test_rolling_deployment[graph1.json-graph3.json-True-contour] _________
[gw1] linux -- Python 3.6.10 /usr/local/bin/python

namespace = 'test-rolling-deployment-graph1-json-graph3-json-true-contour'
api_gateway = 'localhost:8005', from_deployment = 'graph1.json'
to_deployment = 'graph3.json', change = True

    @pytest.mark.flaky(max_runs=3)
    @with_api_gateways
    @pytest.mark.parametrize(
        "from_deployment,to_deployment,change",
        [
            ("graph1.json", "graph2.json", True),  # New image version
            (
                "graph1.json",
                "graph3.json",
                True,
            ),  # New image version and new name of container
            ("graph1.json", "graph4.json", True),  # New resource request but same image
            ("graph1.json", "graph5.json", True),  # Update with multi-deployment new model
            ("graph1.json", "graph8.json", True),  # From v1alpha2 to v1
            ("graph7.json", "graph8.json", False),  # From v1alpha3 to v1
        ],
    )
    def test_rolling_deployment(
        namespace, api_gateway, from_deployment, to_deployment, change
    ):
        from_file_path = to_resources_path(from_deployment)
        retry_run(f"kubectl apply -f {from_file_path} -n {namespace}")
        wait_for_status("mymodel", namespace)
        wait_for_rollout("mymodel", namespace)
>       assert_model("mymodel", namespace, initial=True, endpoint=api_gateway)

test_rolling_updates.py:229: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

sdep_name = 'mymodel'
namespace = 'test-rolling-deployment-graph1-json-graph3-json-true-contour'
initial = True, endpoint = 'localhost:8005'

    def assert_model(sdep_name, namespace, initial=False, endpoint=API_AMBASSADOR):
        _request = initial_rest_request if initial else rest_request
        r = _request(sdep_name, namespace, endpoint=endpoint)
    
>       assert r is not None
E       AssertionError

seldon_e2e_utils.py:592: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
________ test_rolling_deployment[graph1.json-graph4.json-True-contour] _________
[gw3] linux -- Python 3.6.10 /usr/local/bin/python

namespace = 'test-rolling-deployment-graph1-json-graph4-json-true-contour'
api_gateway = 'localhost:8005', from_deployment = 'graph1.json'
to_deployment = 'graph4.json', change = True

    @pytest.mark.flaky(max_runs=3)
    @with_api_gateways
    @pytest.mark.parametrize(
        "from_deployment,to_deployment,change",
        [
            ("graph1.json", "graph2.json", True),  # New image version
            (
                "graph1.json",
                "graph3.json",
                True,
            ),  # New image version and new name of container
            ("graph1.json", "graph4.json", True),  # New resource request but same image
            ("graph1.json", "graph5.json", True),  # Update with multi-deployment new model
            ("graph1.json", "graph8.json", True),  # From v1alpha2 to v1
            ("graph7.json", "graph8.json", False),  # From v1alpha3 to v1
        ],
    )
    def test_rolling_deployment(
        namespace, api_gateway, from_deployment, to_deployment, change
    ):
        from_file_path = to_resources_path(from_deployment)
        retry_run(f"kubectl apply -f {from_file_path} -n {namespace}")
        wait_for_status("mymodel", namespace)
        wait_for_rollout("mymodel", namespace)
>       assert_model("mymodel", namespace, initial=True, endpoint=api_gateway)

test_rolling_updates.py:229: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

sdep_name = 'mymodel'
namespace = 'test-rolling-deployment-graph1-json-graph4-json-true-contour'
initial = True, endpoint = 'localhost:8005'

    def assert_model(sdep_name, namespace, initial=False, endpoint=API_AMBASSADOR):
        _request = initial_rest_request if initial else rest_request
        r = _request(sdep_name, namespace, endpoint=endpoint)
    
>       assert r is not None
E       AssertionError

seldon_e2e_utils.py:592: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
________ test_rolling_deployment[graph1.json-graph8.json-True-contour] _________
[gw3] linux -- Python 3.6.10 /usr/local/bin/python

namespace = 'test-rolling-deployment-graph1-json-graph8-json-true-contour'
api_gateway = 'localhost:8005', from_deployment = 'graph1.json'
to_deployment = 'graph8.json', change = True

    @pytest.mark.flaky(max_runs=3)
    @with_api_gateways
    @pytest.mark.parametrize(
        "from_deployment,to_deployment,change",
        [
            ("graph1.json", "graph2.json", True),  # New image version
            (
                "graph1.json",
                "graph3.json",
                True,
            ),  # New image version and new name of container
            ("graph1.json", "graph4.json", True),  # New resource request but same image
            ("graph1.json", "graph5.json", True),  # Update with multi-deployment new model
            ("graph1.json", "graph8.json", True),  # From v1alpha2 to v1
            ("graph7.json", "graph8.json", False),  # From v1alpha3 to v1
        ],
    )
    def test_rolling_deployment(
        namespace, api_gateway, from_deployment, to_deployment, change
    ):
        from_file_path = to_resources_path(from_deployment)
        retry_run(f"kubectl apply -f {from_file_path} -n {namespace}")
        wait_for_status("mymodel", namespace)
        wait_for_rollout("mymodel", namespace)
>       assert_model("mymodel", namespace, initial=True, endpoint=api_gateway)

test_rolling_updates.py:229: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

sdep_name = 'mymodel'
namespace = 'test-rolling-deployment-graph1-json-graph8-json-true-contour'
initial = True, endpoint = 'localhost:8005'

    def assert_model(sdep_name, namespace, initial=False, endpoint=API_AMBASSADOR):
        _request = initial_rest_request if initial else rest_request
        r = _request(sdep_name, namespace, endpoint=endpoint)
    
>       assert r is not None
E       AssertionError

seldon_e2e_utils.py:592: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
________ test_rolling_deployment[graph7.json-graph8.json-False-contour] ________
[gw3] linux -- Python 3.6.10 /usr/local/bin/python

namespace = 'test-rolling-deployment-graph7-json-graph8-json-false-contour'
api_gateway = 'localhost:8005', from_deployment = 'graph7.json'
to_deployment = 'graph8.json', change = False

    @pytest.mark.flaky(max_runs=3)
    @with_api_gateways
    @pytest.mark.parametrize(
        "from_deployment,to_deployment,change",
        [
            ("graph1.json", "graph2.json", True),  # New image version
            (
                "graph1.json",
                "graph3.json",
                True,
            ),  # New image version and new name of container
            ("graph1.json", "graph4.json", True),  # New resource request but same image
            ("graph1.json", "graph5.json", True),  # Update with multi-deployment new model
            ("graph1.json", "graph8.json", True),  # From v1alpha2 to v1
            ("graph7.json", "graph8.json", False),  # From v1alpha3 to v1
        ],
    )
    def test_rolling_deployment(
        namespace, api_gateway, from_deployment, to_deployment, change
    ):
        from_file_path = to_resources_path(from_deployment)
        retry_run(f"kubectl apply -f {from_file_path} -n {namespace}")
        wait_for_status("mymodel", namespace)
        wait_for_rollout("mymodel", namespace)
>       assert_model("mymodel", namespace, initial=True, endpoint=api_gateway)

test_rolling_updates.py:229: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

sdep_name = 'mymodel'
namespace = 'test-rolling-deployment-graph7-json-graph8-json-false-contour'
initial = True, endpoint = 'localhost:8005'

    def assert_model(sdep_name, namespace, initial=False, endpoint=API_AMBASSADOR):
        _request = initial_rest_request if initial else rest_request
        r = _request(sdep_name, namespace, endpoint=endpoint)
    
>       assert r is not None
E       AssertionError

seldon_e2e_utils.py:592: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
________ test_rolling_deployment[graph1.json-graph5.json-True-contour] _________
[gw1] linux -- Python 3.6.10 /usr/local/bin/python

namespace = 'test-rolling-deployment-graph1-json-graph5-json-true-contour'
api_gateway = 'localhost:8005', from_deployment = 'graph1.json'
to_deployment = 'graph5.json', change = True

    @pytest.mark.flaky(max_runs=3)
    @with_api_gateways
    @pytest.mark.parametrize(
        "from_deployment,to_deployment,change",
        [
            ("graph1.json", "graph2.json", True),  # New image version
            (
                "graph1.json",
                "graph3.json",
                True,
            ),  # New image version and new name of container
            ("graph1.json", "graph4.json", True),  # New resource request but same image
            ("graph1.json", "graph5.json", True),  # Update with multi-deployment new model
            ("graph1.json", "graph8.json", True),  # From v1alpha2 to v1
            ("graph7.json", "graph8.json", False),  # From v1alpha3 to v1
        ],
    )
    def test_rolling_deployment(
        namespace, api_gateway, from_deployment, to_deployment, change
    ):
        from_file_path = to_resources_path(from_deployment)
        retry_run(f"kubectl apply -f {from_file_path} -n {namespace}")
        wait_for_status("mymodel", namespace)
        wait_for_rollout("mymodel", namespace)
>       assert_model("mymodel", namespace, initial=True, endpoint=api_gateway)

test_rolling_updates.py:229: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

sdep_name = 'mymodel'
namespace = 'test-rolling-deployment-graph1-json-graph5-json-true-contour'
initial = True, endpoint = 'localhost:8005'

    def assert_model(sdep_name, namespace, initial=False, endpoint=API_AMBASSADOR):
        _request = initial_rest_request if initial else rest_request
        r = _request(sdep_name, namespace, endpoint=endpoint)
    
>       assert r is not None
E       AssertionError

seldon_e2e_utils.py:592: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
------------------------------ Captured log call -------------------------------
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:169 Failed to find status - sleeping
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
WARNING  root:seldon_e2e_utils.py:213 Bad status:404
===Flaky Test Report===

test_rolling_deployment[graph1.json-graph3.json-True-ambas] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph1.json-graph4.json-True-istio] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph1.json-graph8.json-True-istio] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph7.json-graph8.json-False-ambas] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph7.json-graph8.json-False-istio] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph1.json-graph2.json-True-contour] failed (2 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph2.json-True-contour] failed (1 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph2.json-True-contour] failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph4.json-True-ambas] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph1.json-graph5.json-True-istio] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph1.json-graph8.json-True-ambas] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph1.json-graph2.json-True-ambas] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph1.json-graph3.json-True-istio] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph1.json-graph4.json-True-contour] failed (2 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph4.json-True-contour] failed (1 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph4.json-True-contour] failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph8.json-True-contour] failed (2 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph8.json-True-contour] failed (1 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph8.json-True-contour] failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph7.json-graph8.json-False-contour] failed (2 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph7.json-graph8.json-False-contour] failed (1 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph7.json-graph8.json-False-contour] failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph2.json-True-istio] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph1.json-graph3.json-True-contour] failed (2 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph3.json-True-contour] failed (1 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph3.json-True-contour] failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph5.json-True-ambas] failed (2 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:241>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:582>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:574>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph5.json-True-ambas] passed 1 out of the required 1 times. Success!
test_rolling_deployment[graph1.json-graph5.json-True-contour] failed (2 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph5.json-True-contour] failed (1 runs remaining out of 3).
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]
test_rolling_deployment[graph1.json-graph5.json-True-contour] failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:229>, <TracebackEntry /workspace/source/testing/scripts/seldon_e2e_utils.py:592>]

===End Flaky Test Report===
================== 6 failed, 33 passed in 3415.67s (0:56:55) ===================
make: *** [Makefile:135: test_parallel] Error 1
Test returned errors
kind delete cluster
Deleting cluster "kind" ...
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
[31m
Pipeline failed on stage 'end-to-end' : container 'step-test-end-to-end'. The execution of the pipeline has stopped.[0m
